namespace DataCatalyst.DataRoot;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

public sealed class NativePocoEmitter : ICodeEmitter {
    private readonly InheritanceGraph _graph;
    private readonly string _rootNamespace;
    private readonly string _contextName;

    public NativePocoEmitter(InheritanceGraph graph, string rootNamespace = "GameData", string? contextName = null) {
        _graph = graph; _rootNamespace = rootNamespace;
        _contextName = contextName ?? rootNamespace.Split('.').Last() + "Context";
    }

    public string EmitAll() {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (_rootNamespace.Length > 0) { sb.Append("namespace ").Append(_rootNamespace).AppendLine(";"); sb.AppendLine(); }

        // Nested struct declarations
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            foreach (var f in _graph.FlattenedFields(node)) f.Type.EmitDeclarations(sb, 0);
        }

        // Main structs
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            sb.Append("public struct ").Append(node.Name).AppendLine(" {");
            foreach (var f in _graph.FlattenedFields(node)) {
                sb.Append("    public ").Append(f.CSharpType).Append(" ").Append(f.Name)
                  .Append(" { get; set; }")
                  .AppendLine(f.Type.IsComplex ? " = " + f.CSharpDefault + ";" : "");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Context class
        sb.Append("public static partial class ").Append(_contextName).AppendLine(" {");

        // Static constructor — typed registration per startup struct
        var startupNodes = _graph.Nodes.Values.Where(n => !n.IsCompileEager && !n.IsDslFile).ToList();
        if (startupNodes.Count > 0) {
            sb.Append("    static ").Append(_contextName).AppendLine("() {");

            foreach (var node in startupNodes) {
                var branch = node.Namespace.Split('.')[0];
                branch = branch.Length > 0 ? branch : "_";
                var branchPath = branch + "." + node.Name;
                var fields = _graph.FlattenedFields(node);

                sb.Append("        global::DataCatalyst.Runtime.DataContextRegistry.Register<")
                  .Append(branch).Append(".").Append(node.Name).Append(">(overrideJson => {").AppendLine();
                sb.Append("            if (overrideJson is null) {");
                sb.Append(" ").Append(branchPath).Append(" = new ").Append(node.Name).Append(" {");
                var first = true;
                foreach (var f in fields) {
                    if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                        if (!first) sb.Append(",");
                        sb.Append(" ").Append(f.Name).Append(" = ").Append(f.Type.EmitDefault(LoadHint.Eager, d));
                        first = false;
                    }
                }
                sb.AppendLine(" }; } else {");
                sb.Append("                var _v = ").Append(branchPath).Append(";").AppendLine();
                foreach (var f in fields) {
                    if (f.Type.IsComplex) continue;
                    sb.Append("                if (overrideJson.Value.TryGetProperty(\"").Append(f.Name)
                      .Append("\", out var _j").Append(f.Name).Append(")) _v.").Append(f.Name)
                      .Append(" = ").Append(f.Type.EmitJsonParse("_j" + f.Name)).Append(";").AppendLine();
                }
                sb.Append("                ").Append(branchPath).Append(" = _v;").AppendLine();
                sb.AppendLine("            }");
                sb.AppendLine("        });");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Compile-eager: static readonly fields in branch classes
        var branches = _graph.Nodes.Values.Where(n => !n.IsDslFile)
            .GroupBy(n => { var s = n.Namespace.Split('.')[0]; return s.Length > 0 ? s : "_"; }).ToList();

        foreach (var branch in branches) {
            sb.Append("    public static partial class ").Append(branch.Key).AppendLine(" {");
            foreach (var node in branch) {
                var fields = _graph.FlattenedFields(node);
                if (node.IsCompileEager) {
                    sb.Append("        public static readonly ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" = new ").Append(node.Name).Append(" {");
                    var first = true;
                    foreach (var f in fields) {
                        if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                            if (!first) sb.Append(",");
                            sb.Append(" ").Append(f.Name).Append(" = ").Append(f.Type.EmitDefault(LoadHint.Eager, d));
                            first = false;
                        }
                    }
                    sb.AppendLine(" };");
                } else {
                    sb.Append("        public static ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" { get; internal set; }").AppendLine();
                }
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
