namespace DataCatalyst.DataRoot;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

public sealed class NativePocoEmitter : ICodeEmitter {
    private readonly InheritanceGraph _graph;
    private readonly string _rootNamespace;
    private readonly string _contextName;

    public NativePocoEmitter(InheritanceGraph graph, string rootNamespace = "GameData", string? contextName = null) {
        _graph = graph; _rootNamespace = rootNamespace;
        _contextName = contextName ?? rootNamespace.Split('.').Last() + "Context";
    }

    public string EmitAll() {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (_rootNamespace.Length > 0) {
            sb.Append("namespace ").Append(_rootNamespace).AppendLine(";"); sb.AppendLine();
        }

        // Type declarations (nested structs from complex fields)
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            foreach (var f in _graph.FlattenedFields(node))
                f.Type.EmitDeclarations(sb, 0);
        }

        // Main structs
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            sb.Append("public struct ").Append(node.Name).AppendLine(" {");
            foreach (var f in _graph.FlattenedFields(node)) {
                var init = f.Type.IsComplex ? " = " + f.CSharpDefault + ";" : "";
                sb.Append("    public ").Append(f.CSharpType).Append(" ").Append(f.Name)
                  .Append(" { get; set; }").AppendLine(init);
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Context class
        sb.Append("public static partial class ").Append(_contextName).AppendLine(" {");

        var branches = _graph.Nodes.Values.Where(n => !n.IsDslFile)
            .GroupBy(n => { var s = n.Namespace.Split('.')[0]; return s.Length > 0 ? s : "_"; }).ToList();

        foreach (var branch in branches) {
            sb.Append("    public static partial class ").Append(branch.Key).AppendLine(" {");
            foreach (var node in branch) {
                if (node.IsCompileEager) {
                    var fields = _graph.FlattenedFields(node);
                    sb.Append("        public static readonly ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" = new ").Append(node.Name).Append(" {");
                    var first = true;
                    foreach (var f in fields) {
                        if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                            if (!first) sb.Append(",");
                            sb.Append(" ").Append(f.Name).Append(" = ").Append(f.Type.EmitDefault(LoadHint.Eager, d));
                            first = false;
                        }
                    }
                    sb.AppendLine(" };");
                } else {
                    sb.Append("        public static ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" { get; private set; }").AppendLine();
                }
            }
            sb.AppendLine("    }");
        }

        var startupNodes = _graph.Nodes.Values.Where(n => !n.IsCompileEager && !n.IsDslFile).ToList();
        if (startupNodes.Count > 0) {
            sb.Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]").AppendLine();
            sb.Append("    internal static void Register() =>").AppendLine();
            sb.Append("        global::DataCatalyst.Runtime.DataContextRegistry.Register(Initialize);").AppendLine();
            sb.AppendLine();
            sb.Append("    internal static void Initialize(")
              .Append("global::System.Collections.Generic.IReadOnlyList<global::DataCatalyst.Runtime.DataOverride>? overrides = null) {").AppendLine();

            foreach (var node in startupNodes) {
                var fields = _graph.FlattenedFields(node);
                sb.Append("        var _").Append(node.Name).Append(" = new ").Append(node.Name).Append(" {");
                var first = true;
                foreach (var f in fields) {
                    if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                        if (!first) sb.Append(",");
                        sb.Append(" ").Append(f.Name).Append(" = ").Append(f.Type.EmitDefault(LoadHint.Eager, d));
                        first = false;
                    }
                }
                sb.AppendLine(" };");
            }
            sb.AppendLine("        if (overrides is not null) {");
            sb.AppendLine("            foreach (var o in overrides) {");
            sb.AppendLine("                switch (o.Target) {");
            foreach (var node in startupNodes) {
                sb.Append("                    case \"").Append(node.Name).Append("\": {").AppendLine();
                foreach (var f in _graph.FlattenedFields(node)) {
                    if (f.Type.IsComplex) continue;
                    sb.Append("                        if (o.Fields.TryGetValue(\"").Append(f.Name)
                      .Append("\", out var _v").Append(f.Name).Append(")) _").Append(node.Name)
                      .Append(".").Append(f.Name).Append(" = (").Append(f.Type.CSharpName).Append(")_v").Append(f.Name).Append(";").AppendLine();
                }
                sb.AppendLine("                        break;");
                sb.AppendLine("                    }");
            }
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            foreach (var node in startupNodes) {
                var branch = node.Namespace.Split('.')[0];
                branch = branch.Length > 0 ? branch : "_";
                sb.Append("        ").Append(branch).Append(".").Append(node.Name)
                  .Append(" = _").Append(node.Name).Append(";").AppendLine();
            }
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
