namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;

[DcPlugin(typeof(ITypeEmitter))]
public sealed class EntryExposerEmitter : ITypeEmitter {
    [ModuleInitializer]
    internal static void Register() => DcPluginRegistry.RegisterCompanion(new EntryExposerEmitter());

    public string Name => "EntryExposer";

    public bool Applies(DcGenerationContext ctx) => true;

    public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = ctx.ContainingNamespace;
        if (!string.IsNullOrEmpty(ns)) {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        var t = ctx.SimpleName;
        var enumType = t + "Kind";

        sb.Append("public static class ").Append(t).AppendLine("Exposer {");

        sb.AppendLine("\t[System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("\tinternal static void Register() {");
        sb.Append("\t\tglobal::FM39hz.DataCatalyst.Plugins.Modding.Runtime.EntryExposerRegistry.Register(");
        sb.Append("Expose").AppendLine(");");
        sb.AppendLine("\t}");
        sb.AppendLine();

        sb.Append("\tprivate static void Expose(global::FM39hz.DataCatalyst.Abstractions.IScriptContext ctx)");
        sb.AppendLine(" {");

        EmitAdd(ctx, sb, t, schema);
        EmitGet(ctx, sb, t, schema);
        EmitRemove(ctx, sb, t);
        EmitAddRange(ctx, sb, t, schema);

        sb.AppendLine("\t}");

        // Generate MapFromDict helper
        EmitMapFromDict(sb, t, schema);
        EmitMapToDict(sb, t, schema);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitAdd(DcGenerationContext ctx, StringBuilder sb, string t, SchemaInfo schema) {
        sb.Append("\t\tctx.SetGlobal(\"").Append(t).AppendLine("_Add\",");
        sb.Append("\t\t\t(global::System.Action<string, global::System.Collections.Generic.Dictionary<string, object>>)");
        sb.AppendLine("((key, fields) => {");
        sb.AppendLine("\t\t\t\tvar entry = MapFromDict(fields);");
        sb.Append("\t\t\t\tglobal::").Append(ctx.ContainingNamespace).Append(".").Append(t).AppendLine("Mod.AddEntry(key, entry);");
        sb.AppendLine("\t\t\t}));");
    }

    private static void EmitGet(DcGenerationContext ctx, StringBuilder sb, string t, SchemaInfo schema) {
        sb.Append("\t\tctx.SetGlobal(\"").Append(t).AppendLine("_Get\",");
        sb.Append("\t\t\t(global::System.Func<string, global::System.Collections.Generic.Dictionary<string, object>?>)");
        sb.AppendLine("((string kind) => {");
        sb.Append("\t\t\tif (!global::").Append(ctx.ContainingNamespace).Append(".").Append(t);
        sb.AppendLine(".TryGetKind(kind, out var k)) return null;");
        sb.Append("\t\t\tvar entry = global::").Append(ctx.ContainingNamespace).Append(".").Append(t);
        sb.AppendLine(".Get(k);");
        sb.AppendLine("\t\t\treturn MapToDict(entry);");
        sb.AppendLine("\t\t}));");
    }

    private static void EmitRemove(DcGenerationContext ctx, StringBuilder sb, string t) {
        sb.Append("\t\tctx.SetGlobal(\"").Append(t).AppendLine("_Remove\",");
        sb.Append("\t\t\t(global::System.Action<string>)");
        sb.AppendLine("((string key) => {");
        sb.Append("\t\t\tglobal::").Append(ctx.ContainingNamespace).Append(".").Append(t);
        sb.AppendLine("Mod.RemoveEntry(key);");
        sb.AppendLine("\t\t}));");
    }

    private static void EmitAddRange(DcGenerationContext ctx, StringBuilder sb, string t, SchemaInfo schema) {
        sb.Append("\t\tctx.SetGlobal(\"").Append(t).AppendLine("_AddRange\",");
        sb.Append("\t\t\t(global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, object>>>)");
        sb.AppendLine("((entries) => {");
        sb.AppendLine("\t\t\tforeach (var kv in entries) {");
        sb.AppendLine("\t\t\t\tvar entry = MapFromDict(kv.Value);");
        sb.Append("\t\t\t\tglobal::").Append(ctx.ContainingNamespace).Append(".").Append(t);
        sb.AppendLine("Mod.AddEntry(kv.Key, entry);");
        sb.AppendLine("\t\t\t}");
        sb.AppendLine("\t\t}));");
    }

    private static void EmitMapFromDict(StringBuilder sb, string t, SchemaInfo schema) {
        sb.Append("\tprivate static ").Append(t).AppendLine(" MapFromDict(global::System.Collections.Generic.Dictionary<string, object> fields) {");
        sb.Append("\t\treturn new ").Append(t).AppendLine(" {");
        foreach (var col in schema.Columns) {
            var cast = col.Type.Primitive switch {
                "int" => "int",
                "long" => "long",
                "float" => "float",
                "double" => "double",
                "bool" => "bool",
                _ => "string",
            };
            var def = col.Type.Primitive switch {
                "int" => "0",
                "long" => "0L",
                "float" => "0f",
                "double" => "0d",
                "bool" => "false",
                _ => "\"\"",
            };
            sb.Append("\t\t\t").Append(col.MemberName).Append(" = fields.TryGetValue(\"").Append(col.MemberName);
            sb.Append("\", out var _v").Append(col.MemberName).Append(") ? (").Append(cast).Append(")");
            sb.Append("_v").Append(col.MemberName).Append(" : ").Append(def).AppendLine(",");
        }
        sb.AppendLine("\t\t};");
        sb.AppendLine("\t}");
        sb.AppendLine();
    }

    private static void EmitMapToDict(StringBuilder sb, string t, SchemaInfo schema) {
        sb.Append("\tprivate static global::System.Collections.Generic.Dictionary<string, object> MapToDict(");
        sb.Append(t).AppendLine(" entry) {");
        sb.AppendLine("\t\treturn new global::System.Collections.Generic.Dictionary<string, object> {");
        foreach (var col in schema.Columns) {
            sb.Append("\t\t\t[\"").Append(col.MemberName).Append("\"] = entry.").Append(col.MemberName).AppendLine(",");
        }
        sb.AppendLine("\t\t};");
        sb.AppendLine("\t}");
    }
}
