namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;
using Microsoft.CodeAnalysis;

[DcPlugin(typeof(ITypeEmitter))]
public sealed class LuaBridgeEmitter : ITypeEmitter {
	[ModuleInitializer]
	internal static void Register() => DcPluginRegistry.RegisterCompanion(new LuaBridgeEmitter());

	public string Name => "LuaBridge";

	public bool Applies(DcGenerationContext ctx) => ctx.ModSupport;

	public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var ns = ctx.ContainingNamespace;
		if (!string.IsNullOrEmpty(ns)) {
			sb.Append("namespace ").Append(ns).AppendLine(";");
			sb.AppendLine();
		}

		var t = ctx.SimpleName;
		var modType = t + "Mod";

		sb.Append("public static class ").Append(t).AppendLine("Lua {");
		sb.AppendLine("\tpublic static void Register(global::MoonSharp.Interpreter.Script lua) {");

		EmitRegisterAdd(sb, t, modType, schema);
		sb.AppendLine();

		sb.Append("\t\tlua.Globals[\"").Append(t).Append("_Get\"] = (global::System.Func<string, ").Append(t).Append(">)Get;\n");

		sb.AppendLine("\t}");

		sb.AppendLine();
		EmitAddMethod(sb, t, modType, schema);
		sb.AppendLine();
		EmitGetMethod(sb, t);

		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void EmitRegisterAdd(StringBuilder sb, string typeName, string modType, SchemaInfo schema) {
		var paramList = new List<string> { "string key" };
		var assignList = new List<string>();
		foreach (var col in schema.Columns) {
			var luaType = PrimitiveToLuaType(col.Type.Primitive);
			paramList.Add(luaType + " " + col.MemberName);
			assignList.Add(col.MemberName + " = " + col.MemberName);
		}

		sb.Append("\t\tlua.Globals[\"").Append(typeName).Append("_Add\"] = (global::System.Action<");
		sb.Append(string.Join(", ", paramList.ConvertAll(p => {
			var afterSpace = p.IndexOf(' ') + 1;
			return afterSpace > 0 ? p.Substring(afterSpace) : p;
		}))).Append(">)Add;\n");
	}

	private static void EmitAddMethod(StringBuilder sb, string typeName, string modType, SchemaInfo schema) {
		var paramList = new List<string> { "string key" };
		var assignList = new List<string>();
		foreach (var col in schema.Columns) {
			var luaType = PrimitiveToLuaType(col.Type.Primitive);
			paramList.Add(luaType + " " + col.MemberName);
			assignList.Add(col.MemberName + " = " + col.MemberName);
		}

		sb.Append("\tprivate static void Add(").Append(string.Join(", ", paramList)).AppendLine(") {");
		sb.Append("\t\t").Append(modType).Append(".AddEntry(key, new ").Append(typeName).Append(" { ");
		for (var i = 0; i < assignList.Count; i++) {
			if (i > 0) sb.Append(", ");
			sb.Append(assignList[i]);
		}
		sb.AppendLine(" });");
		sb.AppendLine("\t}");
	}

	private static void EmitGetMethod(StringBuilder sb, string typeName) {
		sb.Append("\tprivate static ").Append(typeName).Append(" Get(string kind) =>\n");
		sb.Append("\t\t").Append(typeName).Append(".TryGetKind(kind, out var k) ? ").Append(typeName).Append(".Get(k) : default;\n");
	}

	private static string PrimitiveToLuaType(string? primitive) =>
		primitive switch {
			"int" => "int",
			"long" => "int",
			"float" => "float",
			"double" => "float",
			"bool" => "bool",
			"string" => "string",
			_ => "string",
		};
}
