namespace DataCatalyst.Plugins.GameConcept;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptsFromDataGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var jsonFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
			.Select(static (f, _) => {
				var key = Path.GetFileNameWithoutExtension(f.Path);
				var text = f.GetText()?.ToString() ?? "";
				return (FileName: key, Text: text);
			})
			.Where(static t => !string.IsNullOrEmpty(t.Text))
			.Collect();

		context.RegisterSourceOutput(jsonFiles, static (spc, files) => {
			var entries = new List<(string Name, string Description)>();

			foreach (var file in files) {
				if (file.FileName == "concepts") {
					entries.AddRange(ParseConcepts(file.Text));
				}
			}

			if (entries.Count == 0) return;

			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using DataCatalyst.Plugins.GameConcept;");
			sb.AppendLine("namespace DataCatalyst.Generated {");

			foreach (var (name, desc) in entries.OrderBy(e => e.Name)) {
				if (!string.IsNullOrEmpty(desc))
					sb.AppendLine($"\t/// <summary>{desc}</summary>");
				sb.AppendLine($"\t[DataConcept(\"{name}\")]");
				sb.AppendLine($"\tpublic readonly partial record struct {name}Concept;");
			}

			sb.AppendLine("}");

			spc.AddSource("ConceptsFromData.g.cs",
				SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}

	private static List<(string Name, string Description)> ParseConcepts(string json) {
		var result = new List<(string Name, string Description)>();
		var idx = 0;

		while (idx < json.Length) {
			// Find next key
			var keyStart = json.IndexOf('"', idx);
			if (keyStart < 0) break;
			var keyEnd = json.IndexOf('"', keyStart + 1);
			if (keyEnd < 0) break;
			var key = json.Substring(keyStart + 1, keyEnd - keyStart - 1);

			// Skip colon
			idx = keyEnd + 1;
			while (idx < json.Length && (json[idx] == ':' || char.IsWhiteSpace(json[idx]))) idx++;

			var desc = "";
			if (idx < json.Length && json[idx] == '{') {
				// New format: "Enemy": { "description": "..." }
				var descIdx = json.IndexOf("\"description\"", idx);
				if (descIdx >= 0) {
					var valStart = json.IndexOf('"', descIdx + 13);
					if (valStart >= 0) {
						var valEnd = json.IndexOf('"', valStart + 1);
						if (valEnd > valStart) {
							desc = json.Substring(valStart + 1, valEnd - valStart - 1);
						}
					}
				}
				var braceEnd = json.IndexOf('}', idx);
				if (braceEnd >= 0) idx = braceEnd + 1;
				else break;
			}
			else if (idx < json.Length && json[idx] == '[') {
				// Old format: "Enemy": ["Goblin"]
				var arrEnd = json.IndexOf(']', idx);
				if (arrEnd >= 0) idx = arrEnd + 1;
				else break;
			}
			else break;

			result.Add((key, desc));
		}

		return result;
	}
}
