namespace DataCatalyst.Plugins.GameConcept;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptsFromDataGenerator : IIncrementalGenerator {
	private const string ConceptsFileName = "concepts";
	private const string DescriptionProp = "description";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var jsonFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
			.Select(static (f, _) => {
				var key = Path.GetFileNameWithoutExtension(f.Path);
				var text = f.GetText()?.ToString() ?? string.Empty;
				return (FileName: key, Text: text);
			})
			.Where(static t => !string.IsNullOrEmpty(t.Text))
			.Collect();

		context.RegisterSourceOutput(jsonFiles, static (spc, files) => {
			var concepts = new List<ConceptInfo>();
			var machineStates = new Dictionary<string, HashSet<string>>();

			foreach (var file in files) {
				if (file.FileName == ConceptsFileName) {
					concepts.AddRange(ParseConcepts(file.Text));
				}
				else {
					ParseStateGroup(file.Text, machineStates);
				}
			}

			Emit(spc, concepts, machineStates);
		});
	}

	private static void ParseStateGroup(string text,
		Dictionary<string, HashSet<string>> machineStates) {
		using var doc = JsonDocument.Parse(text);
		foreach (var prop in doc.RootElement.EnumerateObject()) {
			if (prop.Value.ValueKind != JsonValueKind.Object) continue;
			var groupId = prop.Value.TryGetProperty("GroupId", out var gid) && gid.ValueKind == JsonValueKind.String
				? gid.GetString() : null;
			if (string.IsNullOrEmpty(groupId)) continue;

			if (prop.Value.TryGetProperty("States", out var states) && states.ValueKind == JsonValueKind.Object) {
				if (!machineStates.TryGetValue(groupId!, out var set)) {
					set = new HashSet<string>();
					machineStates[groupId!] = set;
				}
				foreach (var s in states.EnumerateObject()) set.Add(s.Name);
			}
		}
	}

	private static void Emit(SourceProductionContext spc,
		List<ConceptInfo> concepts,
		Dictionary<string, HashSet<string>> machineStates) {

		var members = new List<MemberDeclarationSyntax>();
		var initBody = new List<StatementSyntax>();

		foreach (var c in concepts.OrderBy(c => c.Name)) {
			var conceptMembers = new List<MemberDeclarationSyntax>();

			if (machineStates.TryGetValue(c.Name, out var states) && states.Count > 0) {
				var sorted = states.OrderBy(s => s).ToList();
				// Default state = first alphabetically (index 0)
				conceptMembers.Add(GenerateIntConstant("Default", 0));
				// State constants: 0, 1, 2, ... (skip 0 since it's Default)
				for (int i = 1; i < sorted.Count; i++) {
					conceptMembers.Add(GenerateIntConstant(sorted[i], i));
				}
			}

			var structDecl = StructDeclaration(c.Name)
				.WithModifiers(TokenList(
					Token(SyntaxKind.PublicKeyword),
					Token(SyntaxKind.ReadOnlyKeyword),
					Token(SyntaxKind.PartialKeyword)))
				.WithAttributeLists(SingletonList(
					AttributeList(SingletonSeparatedList(
						Attribute(
							ParseName("DataConcept"),
							AttributeArgumentList(SingletonSeparatedList(
								AttributeArgument(
									LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(c.Name))))))))))
				.AddMembers(conceptMembers.ToArray());

			if (!string.IsNullOrEmpty(c.Description))
				structDecl = structDecl.WithLeadingTrivia(TriviaList(Comment($"/// <summary>{c.Description}</summary>\n")));

			initBody.Add(RegisterCall($"Concept.{c.Name}", c.Name));
			members.Add(structDecl);
		}

		members.Add(ClassDeclaration("Concept")
			.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword), Token(SyntaxKind.PartialKeyword)))
			.AddMembers(members.OfType<StructDeclarationSyntax>().ToArray()));

		members.Add(ClassDeclaration("ConceptRegistrations")
			.WithModifiers(TokenList(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword), Token(SyntaxKind.PartialKeyword)))
			.AddMembers(MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), Identifier("Init"))
				.WithAttributeLists(SingletonList(AttributeList(SingletonSeparatedList(
					Attribute(ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
				.WithModifiers(TokenList(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword)))
				.WithBody(Block(initBody))));

		members.RemoveAll(m => m is StructDeclarationSyntax);

		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
			.AddMembers(
				NamespaceDeclaration(IdentifierName("DataCatalyst.Generated"))
					.WithUsings(SingletonList(UsingDirective(ParseName("DataCatalyst.Plugins.GameConcept"))))
					.AddMembers(members.ToArray()))
			.NormalizeWhitespace(eol: "\n");

		spc.AddSource("ConceptsFromData.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static MemberDeclarationSyntax GenerateIntConstant(string name, int value) {
		return FieldDeclaration(
			VariableDeclaration(PredefinedType(Token(SyntaxKind.IntKeyword)))
				.WithVariables(SingletonSeparatedList(
					VariableDeclarator(Identifier(name))
						.WithInitializer(EqualsValueClause(
							LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value)))))))
			.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.ConstKeyword)));
	}

	private static StatementSyntax RegisterCall(string typeRef, string displayName) {
		var methodAccess = MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
			ParseExpression("global::DataCatalyst.Plugins.GameConcept.ConceptRegistry.Default"),
			GenericName("Register").WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList(ParseTypeName(typeRef)))));
		return ExpressionStatement(InvocationExpression(methodAccess)
			.WithArgumentList(ArgumentList(SingletonSeparatedList(
				Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(displayName)))))));
	}

	private readonly record struct ConceptInfo(string Name, string Description);

	private static List<ConceptInfo> ParseConcepts(string json) {
		var result = new List<ConceptInfo>();
		using var doc = JsonDocument.Parse(json);
		foreach (var prop in doc.RootElement.EnumerateObject()) {
			if (prop.Value.ValueKind != JsonValueKind.Object) continue;
			string desc = string.Empty;
			foreach (var p in prop.Value.EnumerateObject()) {
				if (p.Name == DescriptionProp && p.Value.ValueKind == JsonValueKind.String)
					desc = p.Value.GetString() ?? string.Empty;
			}
			result.Add(new ConceptInfo(prop.Name, desc));
		}
		return result;
	}
}
