namespace DataCatalyst.Plugins.GameConcept;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor StructRequiredError = new(
		id: "DC010",
		title: "DataConcept must be a struct",
		messageFormat: "[DataConcept] on '{0}' is only valid on struct types",
		category: "DataCatalyst.ConceptDomain",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor DuplicateConceptWarning = new(
		id: "DC011",
		title: "Duplicate concept name",
		messageFormat: "[DataConcept] name '{0}' is already registered by '{1}'. Current registration will be overwritten.",
		category: "DataCatalyst.ConceptDomain",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	private const string DataConceptAttr = "DataCatalyst.Plugins.GameConcept.DataConceptAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		// Scan [DataConcept] attributes
		var conceptTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
			DataConceptAttr,
			static (node, _) => node is TypeDeclarationSyntax,
			static (ctx, _) => {
				var t = (INamedTypeSymbol)ctx.TargetSymbol;
				var errorLoc = t.TypeKind != TypeKind.Structure
						? ctx.TargetNode.GetLocation()
						: null;

				var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

				string? conceptName = null;
				var attrClass = ctx.SemanticModel.Compilation.GetTypeByMetadataName(DataConceptAttr);
				foreach (var a in t.GetAttributes()) {
					if (!SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrClass)) continue;
					if (a.ConstructorArguments.Length > 0 && a.ConstructorArguments[0].Value is string name)
						conceptName = name;
					break;
				}

				return new ConceptResult(fullType, conceptName, errorLoc);
			}).Collect();

		context.RegisterSourceOutput(conceptTypes,
			static (spc, cr) => {
				foreach (var c in cr) {
					if (c.ErrorLocation is { } loc)
						spc.ReportDiagnostic(Diagnostic.Create(StructRequiredError, loc));
				}

				var validTypes = cr
					.Where(c => c.FullType != null && c.ConceptName != null)
					.Select(c => (c.FullType!, c.ConceptName!))
					.ToList();

				Emit(spc, validTypes);
			});
	}

	private readonly struct ConceptResult(string? fullType, string? conceptName, Location? errorLocation) {
		public readonly string? FullType = fullType;
		public readonly string? ConceptName = conceptName;
		public readonly Location? ErrorLocation = errorLocation;
	}

	private static void Emit(SourceProductionContext spc,
		List<(string FullType, string ConceptName)> validTypes) {

		// Generate registrations (ModuleInitializer)
		if (validTypes.Count > 0) {
			var initBody = new List<StatementSyntax>();
			foreach (var (ft, name) in validTypes) {
				initBody.Add(BuildRegisterCall(
					"global::DataCatalyst.Plugins.GameConcept.ConceptRegistry.Default",
					ft, name));
			}

			var cu = CompilationUnit()
				.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
				.AddMembers(
					NamespaceDeclaration(IdentifierName("DataCatalyst.Plugins.GameConcept"))
						.AddMembers(
							ClassDeclaration("ConceptRegistrations")
								.WithModifiers(TokenList(
									Token(SyntaxKind.PublicKeyword),
									Token(SyntaxKind.StaticKeyword),
									Token(SyntaxKind.PartialKeyword)))
								.AddMembers(
									MethodDeclaration(
											PredefinedType(Token(SyntaxKind.VoidKeyword)),
											Identifier("Init"))
										.WithAttributeLists(
											SingletonList(
												AttributeList(
													SingletonSeparatedList(
														Attribute(
															ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
										.WithModifiers(TokenList(
											Token(SyntaxKind.InternalKeyword),
											Token(SyntaxKind.StaticKeyword)))
										.WithBody(Block(initBody)))))
				.NormalizeWhitespace();

			spc.AddSource("ConceptRegistrations.g.cs",
				SourceText.From(cu.ToFullString(), Encoding.UTF8));
		}

	}

	private static StatementSyntax BuildRegisterCall(string target, string fullType, string conceptName) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(target),
					GenericName("Register")
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType))))))
				.WithArgumentList(
					ArgumentList(
						SingletonSeparatedList(
							Argument(
								LiteralExpression(
									SyntaxKind.StringLiteralExpression,
									Literal(conceptName)))))));

}
