namespace DataCatalyst.Plugins.GameConcept;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptsFromDataGenerator : IIncrementalGenerator {
	private const string ConceptsFileName = "concepts";
	private const string DescriptionProp = "description";
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var jsonFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
			.Select(static (f, _) => {
				var key = Path.GetFileNameWithoutExtension(f.Path);
				var text = f.GetText()?.ToString() ?? string.Empty;
				return (FileName: key, Text: text);
			})
			.Where(static t => !string.IsNullOrEmpty(t.Text))
			.Collect();

		context.RegisterSourceOutput(jsonFiles, static (spc, files) => {
			var entries = new List<(string Name, string Description)>();

			foreach (var file in files) {
				if (file.FileName == ConceptsFileName) {
					entries.AddRange(ParseConcepts(file.Text));
				}
			}

			if (entries.Count == 0) return;

			var nestedStructs = new List<MemberDeclarationSyntax>();
			foreach (var (name, desc) in entries.OrderBy(e => e.Name)) {
				var structDecl = StructDeclaration(name)
					.WithModifiers(TokenList(
						Token(SyntaxKind.PublicKeyword),
						Token(SyntaxKind.ReadOnlyKeyword),
						Token(SyntaxKind.PartialKeyword)))
					.WithAttributeLists(
						SingletonList(
							AttributeList(
								SingletonSeparatedList(
									Attribute(
										ParseName("DataConcept"),
										AttributeArgumentList(
											SingletonSeparatedList(
												AttributeArgument(
													LiteralExpression(
														SyntaxKind.StringLiteralExpression,
														Literal(name))))))))));

				if (!string.IsNullOrEmpty(desc)) {
					structDecl = structDecl.WithLeadingTrivia(
						TriviaList(
							Comment($"/// <summary>{desc}</summary>\n")));
				}

				nestedStructs.Add(structDecl);
			}

			var conceptClass = ClassDeclaration("Concept")
				.WithModifiers(TokenList(
					Token(SyntaxKind.PublicKeyword),
					Token(SyntaxKind.StaticKeyword),
					Token(SyntaxKind.PartialKeyword)))
				.AddMembers(nestedStructs.ToArray());

			var cu = CompilationUnit()
				.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
				.AddMembers(
					NamespaceDeclaration(IdentifierName("DataCatalyst.Generated"))
						.WithUsings(
							SingletonList(
								UsingDirective(ParseName("DataCatalyst.Plugins.GameConcept"))))
						.AddMembers(conceptClass))
				.NormalizeWhitespace(eol: "\n");

			spc.AddSource("ConceptsFromData.g.cs",
				SourceText.From(cu.ToFullString(), Encoding.UTF8));
		});
	}

	private static List<(string Name, string Description)> ParseConcepts(string json) {
		var result = new List<(string Name, string Description)>();

		using var doc = JsonDocument.Parse(json);
		foreach (var prop in doc.RootElement.EnumerateObject()) {
			var name = prop.Name;
			var desc = string.Empty;

			if (prop.Value.ValueKind == JsonValueKind.Object) {
				if (prop.Value.TryGetProperty(DescriptionProp, out var descEl) && descEl.ValueKind == JsonValueKind.String) {
					desc = descEl.GetString() ?? string.Empty;
				}
			}

			result.Add((name, desc));
		}

		return result;
	}
}
