namespace FM39hz.DataCatalyst.DataRoot;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

public sealed class NativePocoEmitter {
    private readonly InheritanceGraph _graph;
    private readonly string _rootNamespace;
    private readonly string _contextName;

    public NativePocoEmitter(InheritanceGraph graph, string rootNamespace = "GameData", string? contextName = null) {
        _graph = graph;
        _rootNamespace = rootNamespace;
        _contextName = contextName ?? rootNamespace.Split('.').Last() + "Context";
    }

    public string EmitAll() {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = _rootNamespace;
        if (ns.Length > 0) { sb.Append("namespace ").Append(ns).AppendLine(";"); sb.AppendLine(); }

        // Nested types first
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            foreach (var f in _graph.FlattenedFields(node))
                if (f.Kind == FieldKind.Nested) EmitNestedType(sb, f, 0);
        }

        // Structs
        foreach (var node in _graph.Nodes.Values) {
            if (node.IsDslFile) continue;
            var fields = _graph.FlattenedFields(node);
            sb.Append("public struct ").Append(node.Name).AppendLine(" {");
            foreach (var f in fields) {
                sb.Append("    public ").Append(f.CSharpType).Append(" ").Append(f.Name)
                  .Append(" { get; set; }")
                  .AppendLine(f.Kind == FieldKind.Array ? " = " + f.CSharpDefault + ";" : "");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Root context — branches are nested static classes
        sb.Append("public static partial class ").Append(_contextName).AppendLine(" {");

        // Group by branch (first namespace segment)
        var branches = _graph.Nodes.Values
            .Where(n => !n.IsDslFile)
            .GroupBy(n => {
                var s = n.Namespace.Split('.')[0];
                return s.Length > 0 ? s : "_";
            })
            .ToList();

        foreach (var branch in branches) {
            var branchName = branch.Key;
            sb.Append("    public static partial class ").Append(branchName).AppendLine(" {");

            foreach (var node in branch) {
                if (node.IsCompileEager) {
                    var fields = _graph.FlattenedFields(node);
                    sb.Append("        public static readonly ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" = new ").Append(node.Name).Append(" {");
                    var first = true;
                    foreach (var f in fields) {
                        if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                            if (!first) sb.Append(",");
                            sb.Append(" ").Append(f.Name).Append(" = "); EmitValue(sb, f, d); first = false;
                        }
                    }
                    sb.AppendLine(" };");
                } else {
                    sb.Append("        public static ").Append(node.Name).Append(" ").Append(node.Name)
                      .Append(" { get; private set; }").AppendLine();
                }
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ModuleInitializer + Initialize cho startup nodes
        var startupNodes = _graph.Nodes.Values.Where(n => !n.IsCompileEager && !n.IsDslFile).ToList();
        if (startupNodes.Count > 0) {
            sb.Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]").AppendLine();
            sb.Append("    internal static void Register() =>").AppendLine();
            sb.Append("        global::FM39hz.DataCatalyst.Runtime.DataContextRegistry.Register(Initialize);").AppendLine();
            sb.AppendLine();

            sb.Append("    internal static void Initialize(")
              .Append("global::System.Collections.Generic.IReadOnlyList<global::FM39hz.DataCatalyst.Runtime.DataOverride>? overrides = null) {").AppendLine();

            foreach (var node in startupNodes) {
                var fields = _graph.FlattenedFields(node);
                var branch = node.Namespace.Split('.')[0];
                branch = branch.Length > 0 ? branch : "_";
                sb.Append("        var _").Append(node.Name).Append(" = new ").Append(node.Name).Append(" {");
                var first = true;
                foreach (var f in fields) {
                    if (node.Defaults.TryGetValue(f.Name, out var d) && d is not null) {
                        if (!first) sb.Append(",");
                        sb.Append(" ").Append(f.Name).Append(" = "); EmitValue(sb, f, d); first = false;
                    }
                }
                sb.AppendLine(" };");
            }

            sb.AppendLine();
            sb.AppendLine("        if (overrides is not null) {");
            sb.AppendLine("            foreach (var o in overrides) {");
            sb.AppendLine("                switch (o.Target) {");
            foreach (var node in startupNodes) {
                sb.Append("                    case \"").Append(node.Name).Append("\": {").AppendLine();
                foreach (var f in _graph.FlattenedFields(node)) {
                    if (f.Kind == FieldKind.Nested || f.Kind == FieldKind.Array) continue;
                    sb.Append("                        if (o.Fields.TryGetValue(\"").Append(f.Name)
                      .Append("\", out var _v").Append(f.Name).Append(")) _").Append(node.Name)
                      .Append(".").Append(f.Name).Append(" = (").Append(f.Type).Append(")_v").Append(f.Name).Append(";").AppendLine();
                }
                sb.AppendLine("                        break;");
                sb.AppendLine("                    }");
            }
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            foreach (var node in startupNodes) {
                var branch = node.Namespace.Split('.')[0];
                branch = branch.Length > 0 ? branch : "_";
                sb.Append("        ").Append(branch).Append(".").Append(node.Name)
                  .Append(" = _").Append(node.Name).Append(";").AppendLine();
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitNestedType(StringBuilder sb, FieldDefinition field, int indent) {
        var ind = new string('\t', indent);
        sb.Append(ind).Append("public partial struct ").Append(FieldDefinition.NestedTypeName(field.Name)).AppendLine(" {");
        foreach (var sub in field.NestedFields) {
            if (sub.Kind == FieldKind.Nested) EmitNestedType(sb, sub, indent + 1);
            sb.Append(ind).Append('\t').Append("public ").Append(sub.CSharpType).Append(" ").Append(sub.Name)
              .Append(" { get; set; }").AppendLine();
        }
        sb.Append(ind).AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitValue(StringBuilder sb, FieldDefinition f, object value) {
        switch (f.Type) {
            case "int":    sb.Append(value); break;
            case "float":  sb.Append(value).Append("f"); break;
            case "bool":   sb.Append((bool)value ? "true" : "false"); break;
            case "string": sb.Append('"').Append(Escape(value.ToString() ?? "")).Append('"'); break;
            default:       sb.Append("default"); break;
        }
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
