namespace FM39hz.DataCatalyst.DataRoot;

using System.Collections.Generic;
using System.Linq;
using System.Text;

public sealed class NativePocoEmitter {
    private readonly InheritanceGraph _graph;
    private readonly string _rootNamespace;

    public NativePocoEmitter(InheritanceGraph graph, string rootNamespace = "GameData") {
        _graph = graph;
        _rootNamespace = rootNamespace;
    }

    public string EmitAll() {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(_rootNamespace).AppendLine(" {");

        // Structs
        foreach (var node in _graph.Nodes.Values) {
            var fields = _graph.FlattenedFields(node);
            sb.Append("    public struct ").Append(node.Name).AppendLine(" {");
            foreach (var f in fields) {
                sb.Append("        public ").Append(f.CSharpType).Append(" ").Append(f.Name)
                  .Append(" { get; set; }").AppendLine();
            }
            sb.AppendLine("    }");
        }

        var ctxName = _rootNamespace.Split('.').Last() + "Context";
        sb.Append("    public static partial class ").Append(ctxName).AppendLine(" {");

        // Compile-eager: static readonly fields — baked literal, zero runtime
        EmitCompileNodes(sb, ctxName);

        // Startup: static properties with Initialize() — moddable at startup
        EmitStartupNodes(sb, ctxName);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitCompileNodes(StringBuilder sb, string ctxName) {
        var compileNodes = _graph.Nodes.Values.Where(n => n.IsCompileEager).ToList();
        if (compileNodes.Count == 0) return;

        foreach (var node in compileNodes) {
            var fields = _graph.FlattenedFields(node);
            sb.Append("        public static readonly ").Append(node.Name).Append(" ").Append(node.Name)
              .Append(" = new ").Append(node.Name).Append(" {");
            var first = true;
            foreach (var f in fields) {
                if (node.Defaults.TryGetValue(f.Name, out var dflt) && dflt is not null) {
                    if (!first) sb.Append(",");
                    sb.Append(" ").Append(f.Name).Append(" = ");
                    EmitValue(sb, f, dflt);
                    first = false;
                }
            }
            sb.AppendLine(" };");
        }
        sb.AppendLine();
    }

    private void EmitStartupNodes(StringBuilder sb, string ctxName) {
        var startupNodes = _graph.Nodes.Values.Where(n => !n.IsCompileEager).ToList();
        if (startupNodes.Count == 0) return;

        // ModuleInitializer
        sb.Append("        [global::System.Runtime.CompilerServices.ModuleInitializer]").AppendLine();
        sb.Append("        internal static void Register() =>").AppendLine();
        sb.Append("            global::FM39hz.DataCatalyst.Runtime.DataContextRegistry.Register(Initialize);").AppendLine();
        sb.AppendLine();

        // Static properties
        foreach (var node in startupNodes) {
            sb.Append("        public static ").Append(node.Name).Append(" ").Append(node.Name)
              .Append(" { get; private set; }").AppendLine();
        }
        sb.AppendLine();

        // Initialize
        sb.Append("        public static void Initialize(")
          .Append("global::System.Collections.Generic.IReadOnlyList<global::FM39hz.DataCatalyst.Runtime.DataOverride>? overrides = null) {").AppendLine();

        foreach (var node in startupNodes) {
            var fields = _graph.FlattenedFields(node);
            sb.Append("            var _").Append(node.Name).Append(" = new ").Append(node.Name).Append(" {");
            var first = true;
            foreach (var f in fields) {
                if (node.Defaults.TryGetValue(f.Name, out var dflt) && dflt is not null) {
                    if (!first) sb.Append(",");
                    sb.Append(" ").Append(f.Name).Append(" = ");
                    EmitValue(sb, f, dflt);
                    first = false;
                }
            }
            sb.AppendLine(" };");
        }

        sb.AppendLine();
        sb.AppendLine("            if (overrides is not null) {");
        sb.AppendLine("                foreach (var o in overrides) {");
        sb.AppendLine("                    switch (o.Target) {");
        foreach (var node in startupNodes) {
            sb.Append("                        case \"").Append(node.Name).Append("\": {").AppendLine();
            foreach (var f in _graph.FlattenedFields(node)) {
                sb.Append("                            if (o.Fields.TryGetValue(\"").Append(f.Name)
                  .Append("\", out var _v").Append(f.Name).Append(")) _").Append(node.Name)
                  .Append(".").Append(f.Name).Append(" = (").Append(f.Type).Append(")_v").Append(f.Name).Append(";").AppendLine();
            }
            sb.AppendLine("                            break;");
            sb.AppendLine("                        }");
        }
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");

        foreach (var node in startupNodes) {
            sb.Append("            ").Append(node.Name).Append(" = _").Append(node.Name).Append(";").AppendLine();
        }
        sb.AppendLine("        }");
    }

    private static void EmitValue(StringBuilder sb, FieldDefinition f, object value) {
        switch (f.Type) {
            case "int":    sb.Append(value); break;
            case "float":  sb.Append(value).Append("f"); break;
            case "bool":   sb.Append((bool)value ? "true" : "false"); break;
            case "string": sb.Append('"').Append(Escape(value.ToString() ?? "")).Append('"'); break;
            default:       sb.Append("default"); break;
        }
    }

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
