using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace DataCatalyst.V2;

[Generator]
public sealed class AspectGenerator : IIncrementalGenerator
{
    private const string GameAspectAttr = "DataCatalyst.Attributes.GameAspectAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var aspects = context.SyntaxProvider.ForAttributeWithMetadataName(
            GameAspectAttr,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) =>
            {
                var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var name = typeSymbol.Name;

                var fields = typeSymbol.GetMembers().OfType<IFieldSymbol>()
                    .Where(f => f.DeclaredAccessibility == Accessibility.Public)
                    .Select(f => f.Name)
                    .ToArray();

                return new AspectInfo(fullType, name, string.Join(",", fields));
            }).Collect();

        context.RegisterSourceOutput(aspects, static (spc, list) =>
        {
            if (list.Length == 0) return;

            // Count short-name collisions
            var counts = new Dictionary<string, int>();
            foreach (var a in list)
            {
                counts.TryGetValue(a.ShortName, out var c);
                counts[a.ShortName] = c + 1;
            }

            var entries = new List<MemberDeclarationSyntax>();

            for (int i = 0; i < list.Length; i++)
            {
                var a = list[i];
                var discriminator = counts[a.ShortName] > 1 ? a.FullType : $"global::{a.FullType}";
                var idValue = i;

                var entry = ParseMemberDeclaration(
                    $"public static readonly int {a.ShortName} = {idValue};"
                );
                if (entry != null) entries.Add((MemberDeclarationSyntax)entry);
            }

            var classDecl = ClassDeclaration("AspectId")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.StaticKeyword)))
                .WithMembers(List(entries));

            // Generate AspectRegistrations class
            var registerStatements = new List<StatementSyntax>();
            foreach (var a in list)
            {
                var stmt = ParseStatement(
                    $"global::DataCatalyst.Storage.AspectTypeRegistry.Register(typeof({a.FullType}));\n"
                );
                if (stmt != null) registerStatements.Add(stmt);
            }

            var regClass = ClassDeclaration("AspectRegistrations")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.InternalKeyword),
                    Token(SyntaxKind.StaticKeyword)))
                .AddMembers(
                    MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "Init")
                        .WithAttributeLists(SingletonList(
                            AttributeList(SingletonSeparatedList(
                                Attribute(ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
                        .WithModifiers(TokenList(
                            Token(SyntaxKind.InternalKeyword),
                            Token(SyntaxKind.StaticKeyword)))
                        .WithBody(Block(registerStatements)));

            var nsDecl = NamespaceDeclaration(ParseName("DataCatalyst.Generated"))
                .AddMembers(classDecl, regClass);

            var cu = CompilationUnit()
                .WithLeadingTrivia(Comment("// <auto-generated/>"))
                .WithMembers(SingletonList<MemberDeclarationSyntax>(nsDecl))
                .NormalizeWhitespace();

            spc.AddSource("AspectIds.g.cs", SourceText.From(cu.ToFullString(), Encoding.UTF8));
        });
    }

    private readonly record struct AspectInfo(string FullType, string ShortName, string Fields);
}
