namespace DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ComponentGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor StructRequiredError = new(
		id: "DC001",
		title: "DataComponent must be a struct",
		messageFormat: "[DataComponent] on '{0}' is only valid on struct types",
		category: "DataCatalyst",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor CollisionWarning = new(
		id: "DC002",
		title: "Discriminator collision",
		messageFormat: "[DataComponent] types with short name '{0}' collide. Resolved discriminators: '{1}'. Use these fully-qualified strings in JSON.",
		category: "DataCatalyst",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	private const string DataComponentAttr = "DataCatalyst.Abstractions.DataComponentAttribute";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var primitives = context.SyntaxProvider.ForAttributeWithMetadataName(
			DataComponentAttr,
			static (node, _) => node is TypeDeclarationSyntax,
			static (ctx, _) => {
				var t = (INamedTypeSymbol)ctx.TargetSymbol;
				var errorLoc = t.TypeKind != TypeKind.Structure
						? ctx.TargetNode.GetLocation()
						: null;
				var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				var shortName = t.Name;
				var nsQualified = fullType.StartsWith("global::") ? fullType.Substring(8) : fullType;
				nsQualified = nsQualified.Replace('+', '.');
				return new ComponentResult(fullType, shortName, nsQualified, errorLoc);
			}).Collect();

		context.RegisterSourceOutput(primitives,
			static (spc, pr) => {
				foreach (var p in pr) {
					if (p.ErrorLocation is { } loc) {
						spc.ReportDiagnostic(Diagnostic.Create(StructRequiredError, loc));
					}
				}

				Emit(spc, pr);
			});
	}

	private readonly struct ComponentResult(string? fullType, string? shortName, string? nsQualified, Location? errorLocation) {
		public readonly string? FullType = fullType;
		public readonly string? ShortName = shortName;
		public readonly string? NsQualified = nsQualified;
		public readonly Location? ErrorLocation = errorLocation;
	}

	private static void Emit(SourceProductionContext spc,
		ImmutableArray<ComponentResult> allPrims) {

		// First pass: count short-name occurrences for collision detection
		var counts = new Dictionary<string, int>();
		var shortToNs = new Dictionary<string, List<string>>();

		foreach (var p in allPrims) {
			if (p.FullType == null || p.ShortName == null || p.NsQualified == null) {
				continue;
			}

			counts.TryGetValue(p.ShortName, out var c);
			counts[p.ShortName] = c + 1;
			if (!shortToNs.ContainsKey(p.ShortName)) {
				shortToNs[p.ShortName] = [];
			}

			shortToNs[p.ShortName].Add(p.NsQualified);
		}

		// Second pass: build final list (short if unique, ns-qualified if colliding)
		var prims = new List<(string FullType, string Discrim)>();
		foreach (var p in allPrims) {
			if (p.FullType == null || p.NsQualified == null || p.ShortName == null) {
				continue;
			}

			var finalD = counts[p.ShortName] > 1 ? p.NsQualified : p.ShortName;
			prims.Add((p.FullType, finalD));
		}

		// Report collisions with resolved discriminator info
		foreach (var kv in counts) {
			if (kv.Value <= 1) {
				continue;
			}

			var msg = shortToNs.TryGetValue(kv.Key, out var list) ? string.Join(", ", list) : "";
			spc.ReportDiagnostic(Diagnostic.Create(CollisionWarning, Location.None, kv.Key, msg));
		}

		if (prims.Count == 0) {
			return;
		}

		var initBody = new List<StatementSyntax>();
		foreach (var (ft, _) in prims) {
			initBody.Add(BuildRegisterCall("global::DataCatalyst.Core.PrimitiveRegistry.Default", ft));
		}
		initBody.Add(BuildRegisterIdsStatement(prims));

		var regBody = new List<StatementSyntax>();
		foreach (var (ft, _) in prims) {
			regBody.Add(BuildGenericCall("registry", "RegisterComponent", ft));
		}

		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
			.AddMembers(
				NamespaceDeclaration(IdentifierName("DataCatalyst.Core"))
					.AddMembers(
						ClassDeclaration("ComponentRegistrations")
							.WithModifiers(TokenList(
								Token(SyntaxKind.PublicKeyword),
								Token(SyntaxKind.StaticKeyword),
								Token(SyntaxKind.PartialKeyword)))
							.AddMembers(
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("Init"))
									.WithAttributeLists(
										SingletonList(
											AttributeList(
												SingletonSeparatedList(
													Attribute(
														ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
									.WithModifiers(TokenList(
										Token(SyntaxKind.InternalKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithBody(Block(initBody)),
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("RegisterTo"))
									.WithModifiers(TokenList(
										Token(SyntaxKind.PublicKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithParameterList(
										ParameterList(
											SingletonSeparatedList(
												Parameter(Identifier("registry"))
													.WithType(
														ParseTypeName("global::DataCatalyst.Core.DataRegistry")))))
									.WithBody(Block(regBody))))
					)
			.NormalizeWhitespace();

		spc.AddSource("ComponentRegistrations.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static StatementSyntax BuildRegisterCall(string target, string fullType) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(target),
					GenericName("Register")
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));

	private static StatementSyntax BuildGenericCall(string instance, string method, string fullType) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(instance),
					GenericName(method)
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));

	private static StatementSyntax BuildRegisterIdsStatement(List<(string FullType, string Discrim)> prims) {
		var elems = new List<ExpressionSyntax>();
		foreach (var (ft, d) in prims) {
			elems.Add(
				InitializerExpression(
					SyntaxKind.ComplexElementInitializerExpression,
					SeparatedList(
						new ExpressionSyntax[] {
							LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(d)),
							TypeOfExpression(ParseTypeName(ft))
						})));
		}

		return ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression("global::DataCatalyst.Core.PrimitiveRegistry.Default"),
					IdentifierName("RegisterIds")))
				.WithArgumentList(
					ArgumentList(
						SingletonSeparatedList(
							Argument(
								ObjectCreationExpression(
									ParseTypeName("global::System.Collections.Generic.Dictionary<string, global::System.Type>"))
									.WithInitializer(
										InitializerExpression(
											SyntaxKind.CollectionInitializerExpression,
											SeparatedList(elems))))))));
	}
}
