namespace DataCatalyst;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor StructRequiredError = new(
		id: "DC010",
		title: "DataConcept must be a struct",
		messageFormat: "[DataConcept] on '{0}' is only valid on struct types",
		category: "DataCatalyst.ConceptDomain",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor DuplicateConceptWarning = new(
		id: "DC011",
		title: "Duplicate concept name",
		messageFormat: "[DataConcept] name '{0}' is already registered by '{1}'. Current registration will be overwritten.",
		category: "DataCatalyst.ConceptDomain",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	private const string DataConceptAttr = "DataCatalyst.Core.DataConceptAttribute";
	private const string AttrKindArg = "Kind";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var conceptTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
			DataConceptAttr,
			static (node, _) => node is TypeDeclarationSyntax,
			static (ctx, _) => {
				var t = (INamedTypeSymbol)ctx.TargetSymbol;
				var errorLoc = t.TypeKind != TypeKind.Structure
						? ctx.TargetNode.GetLocation()
						: null;

				var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

				string? conceptName = null;
				var conceptKind = 0;
				var attrClass = ctx.SemanticModel.Compilation.GetTypeByMetadataName(DataConceptAttr);
				foreach (var a in t.GetAttributes()) {
					if (!SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrClass)) continue;
					foreach (var arg in a.ConstructorArguments) {
						if (arg.Value is string name) conceptName = name;
					}
					foreach (var n in a.NamedArguments) {
						if (n.Key == AttrKindArg && n.Value.Value is int kind) conceptKind = kind;
					}
					break;
				}

				return new ConceptResult(fullType, conceptName, conceptKind, errorLoc);
			}).Collect();

		var configs = ConfigHelper.GetConfigs(context);
		var combined = conceptTypes.Combine(configs);

		context.RegisterSourceOutput(combined,
			static (spc, data) => {
				var (cr, configs) = data;

				foreach (var c in cr) {
					if (c.ErrorLocation is { } loc)
						spc.ReportDiagnostic(Diagnostic.Create(StructRequiredError, loc));
				}

				var validTypes = cr
					.Where(c => c.FullType != null && c.ConceptName != null)
					.Select(c => (c.FullType!, c.ConceptName!, c.ConceptKind))
					.ToList();

				Emit(spc, validTypes, configs.Length > 0 ? configs[0] : new SourceConfig("", "DataCatalyst.Generated", new List<string>()));
			});
	}

	private readonly struct ConceptResult(string? fullType, string? conceptName, int conceptKind, Location? errorLocation) {
		public readonly string? FullType = fullType;
		public readonly string? ConceptName = conceptName;
		public readonly int ConceptKind = conceptKind;
		public readonly Location? ErrorLocation = errorLocation;
	}

	private static void Emit(SourceProductionContext spc,
		List<(string FullType, string ConceptName, int Kind)> validTypes,
		SourceConfig config) {

		if (validTypes.Count == 0) return;

		var ns = string.IsNullOrEmpty(config.Namespace) ? "DataCatalyst.Generated" : config.Namespace;
		var initBody = new List<StatementSyntax>();
		foreach (var (ft, name, kind) in validTypes) {
			initBody.Add(BuildRegisterCall(
				"global::DataCatalyst.Core.ConceptRegistry.Default",
				ft, name, kind));
		}

		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"));

		cu = cu.AddMembers(
				NamespaceDeclaration(IdentifierName(ns))
					.AddMembers(
						ClassDeclaration("AttributeConceptRegistrations")
							.WithModifiers(TokenList(
								Token(SyntaxKind.PublicKeyword),
								Token(SyntaxKind.StaticKeyword),
								Token(SyntaxKind.PartialKeyword)))
							.AddMembers(
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("Init"))
									.WithAttributeLists(
										SingletonList(
											AttributeList(
												SingletonSeparatedList(
													Attribute(
														ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
									.WithModifiers(TokenList(
										Token(SyntaxKind.InternalKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithBody(Block(initBody)))))
			.NormalizeWhitespace();

		spc.AddSource("AttributeConceptRegistrations.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static StatementSyntax BuildRegisterCall(string target, string fullType, string conceptName, int kind = 0) {
		var factoryExpr = ParenthesizedLambdaExpression(
			ParameterList(SeparatedList(new[] {
				Parameter(Identifier("entries")),
				Parameter(Identifier("name"))
			})),
			ObjectCreationExpression(
				GenericName(Identifier("global::DataCatalyst.Core.ConceptCatalog"))
					.WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList(ParseTypeName(fullType)))))
				.WithArgumentList(ArgumentList(SeparatedList(new[] {
					Argument(IdentifierName("entries")),
					Argument(IdentifierName("name"))
				}))));

		var args = new List<ArgumentSyntax> {
			Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(conceptName))),
			Argument(factoryExpr)
		};
		if (kind != 0) {
			args.Add(Argument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(kind))));
		}
		return ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(target),
					GenericName("Register")
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType))))))
				.WithArgumentList(ArgumentList(SeparatedList(args))));
	}
}
