namespace DataCatalyst;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class ConceptsFromDataGenerator : IIncrementalGenerator {
	private const string ConceptsFileName = "concepts";
	private const string DescriptionProp = "description";
	private const string KindProp = "kind";
	private const string ConceptProp = "Concept";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var jsonFiles = context.AdditionalTextsProvider
			.Where(static f => f.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
			.Select(static (f, _) => {
				var key = Path.GetFileNameWithoutExtension(f.Path);
				var text = f.GetText()?.ToString() ?? string.Empty;
				var dir = Path.GetDirectoryName(f.Path) ?? "";
				return (FileName: key, Text: text, Dir: dir);
			})
			.Where(static t => !string.IsNullOrEmpty(t.Text))
			.Collect();

		var config = ConfigHelper.GetConfig(context);
		var combined = jsonFiles.Combine(config);

		context.RegisterSourceOutput(combined, static (spc, data) => {
			var (files, cfg) = data;
			var concepts = new List<ConceptInfo>();
			var conceptMembers = new Dictionary<string, List<string>>();

			foreach (var file in files) {
				if (file.FileName == ConceptsFileName) {
					concepts.AddRange(ParseConcepts(file.Text));
				}
				else if (!string.Equals(file.FileName, "datacatalyst", StringComparison.OrdinalIgnoreCase)) {
					ParseConceptMembers(file.Text, conceptMembers);
				}
			}

			Emit(spc, concepts, conceptMembers, cfg);
		});
	}

	private static void ParseConceptMembers(string text,
		Dictionary<string, List<string>> conceptMembers) {
		using var doc = JsonDocument.Parse(text);
		foreach (var prop in doc.RootElement.EnumerateObject()) {
			if (prop.Value.ValueKind != JsonValueKind.Object) continue;
			if (!prop.Value.TryGetProperty(ConceptProp, out var conceptEl) || conceptEl.ValueKind != JsonValueKind.String)
				continue;

			var conceptName = conceptEl.GetString();
			if (string.IsNullOrEmpty(conceptName)) continue;

			if (!conceptMembers.TryGetValue(conceptName, out var list)) {
				list = new List<string>();
				conceptMembers[conceptName] = list;
			}
			list.Add(prop.Name);
		}
	}

	private static void Emit(SourceProductionContext spc,
		List<ConceptInfo> concepts,
		Dictionary<string, List<string>> conceptMembers,
		AssemblyConfig config) {

		var members = new List<MemberDeclarationSyntax>();
		var initBody = new List<StatementSyntax>();

		foreach (var c in concepts.OrderBy(c => c.Name)) {
			var conceptMembersList = new List<MemberDeclarationSyntax>();

			if (conceptMembers.TryGetValue(c.Name, out var entryNames) && entryNames.Count > 0) {
				var sorted = entryNames.OrderBy(s => s).ToList();
				for (int i = 0; i < sorted.Count; i++) {
					conceptMembersList.Add(GenerateIntConstant(sorted[i], i));
				}
			}

			var structDecl = StructDeclaration(c.Name)
				.WithModifiers(TokenList(
					Token(SyntaxKind.PublicKeyword),
					Token(SyntaxKind.ReadOnlyKeyword),
					Token(SyntaxKind.PartialKeyword)))
				.WithAttributeLists(SingletonList(
					AttributeList(SingletonSeparatedList(
						Attribute(
							ParseName("DataCatalyst.Core.DataConcept"),
							AttributeArgumentList(SingletonSeparatedList(
								AttributeArgument(
									LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(c.Name))))))))))
				.AddMembers(conceptMembersList.ToArray());

			if (!string.IsNullOrEmpty(c.Description))
				structDecl = structDecl.WithLeadingTrivia(TriviaList(Comment($"/// <summary>{c.Description}</summary>\n")));

			initBody.Add(RegisterCall($"Concept.{c.Name}", c.Name));
			members.Add(structDecl);
		}

		members.Add(ClassDeclaration("Concept")
			.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword), Token(SyntaxKind.PartialKeyword)))
			.AddMembers(members.OfType<StructDeclarationSyntax>().ToArray()));

		members.Add(ClassDeclaration("ConceptRegistrations")
			.WithModifiers(TokenList(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword), Token(SyntaxKind.PartialKeyword)))
			.AddMembers(MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), Identifier("Init"))
				.WithAttributeLists(SingletonList(AttributeList(SingletonSeparatedList(
					Attribute(ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
				.WithModifiers(TokenList(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword)))
				.WithBody(Block(initBody))));

		members.RemoveAll(m => m is StructDeclarationSyntax);

		var ns = config.Namespace;
		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"));

		cu = cu.AddMembers(
				NamespaceDeclaration(IdentifierName(ns))
					.WithUsings(SingletonList(UsingDirective(ParseName("DataCatalyst.Core"))))
					.AddMembers(members.ToArray()))
			.NormalizeWhitespace(eol: "\n");

		spc.AddSource("ConceptsFromData.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static MemberDeclarationSyntax GenerateIntConstant(string name, int value) {
		return FieldDeclaration(
			VariableDeclaration(PredefinedType(Token(SyntaxKind.IntKeyword)))
				.WithVariables(SingletonSeparatedList(
					VariableDeclarator(Identifier(name))
						.WithInitializer(EqualsValueClause(
							LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value)))))))
			.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.ConstKeyword)));
	}

	private static StatementSyntax RegisterCall(string typeRef, string displayName) {
		var methodAccess = MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
			ParseExpression("global::DataCatalyst.Core.ConceptRegistry.Default"),
			GenericName("Register").WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList(ParseTypeName(typeRef)))));
		return ExpressionStatement(InvocationExpression(methodAccess)
			.WithArgumentList(ArgumentList(SingletonSeparatedList(
				Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(displayName)))))));
	}

	private readonly record struct ConceptInfo(string Name, string Description, string Kind);

	private static List<ConceptInfo> ParseConcepts(string json) {
		var result = new List<ConceptInfo>();
		using var doc = JsonDocument.Parse(json);
		foreach (var prop in doc.RootElement.EnumerateObject()) {
			if (prop.Value.ValueKind != JsonValueKind.Object) continue;
			string desc = string.Empty;
			string kind = string.Empty;
			foreach (var p in prop.Value.EnumerateObject()) {
				if (p.Name == DescriptionProp && p.Value.ValueKind == JsonValueKind.String)
					desc = p.Value.GetString() ?? string.Empty;
				if (p.Name == KindProp && p.Value.ValueKind == JsonValueKind.String)
					kind = p.Value.GetString() ?? string.Empty;
			}
			result.Add(new ConceptInfo(prop.Name, desc, kind));
		}
		return result;
	}
}
