namespace DataCatalyst;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class EntryKeysGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var fileKeys = context.AdditionalTextsProvider
			.Select(static (f, _) => Path.GetFileNameWithoutExtension(f.Path))
			.Where(static k => !string.IsNullOrEmpty(k))
			.Collect();

		context.RegisterSourceOutput(fileKeys, static (spc, files) => {
			var distinct = files.Distinct(StringComparer.Ordinal).OrderBy(k => k).ToList();
			if (distinct.Count == 0) return;

			var members = new List<MemberDeclarationSyntax>();
			for (var i = 0; i < distinct.Count; i++) {
				members.Add(
					FieldDeclaration(
						VariableDeclaration(
								PredefinedType(Token(SyntaxKind.IntKeyword)))
							.WithVariables(
								SingletonSeparatedList(
									VariableDeclarator(Identifier(distinct[i]))
										.WithInitializer(
											EqualsValueClause(
												LiteralExpression(
													SyntaxKind.NumericLiteralExpression,
													Literal(i)))))))
						.WithModifiers(TokenList(
							Token(SyntaxKind.PublicKeyword),
							Token(SyntaxKind.ConstKeyword))));
			}

			// Add Count field
			members.Add(
				FieldDeclaration(
					VariableDeclaration(
							PredefinedType(Token(SyntaxKind.IntKeyword)))
						.WithVariables(
							SingletonSeparatedList(
								VariableDeclarator(Identifier("Count"))
									.WithInitializer(
										EqualsValueClause(
											LiteralExpression(
												SyntaxKind.NumericLiteralExpression,
												Literal(distinct.Count)))))))
					.WithModifiers(TokenList(
						Token(SyntaxKind.PublicKeyword),
						Token(SyntaxKind.ConstKeyword))));

			var cu = CompilationUnit()
				.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
				.AddMembers(
					NamespaceDeclaration(IdentifierName("DataCatalyst.Generated"))
						.AddMembers(
							ClassDeclaration("Keys")
								.WithModifiers(TokenList(
									Token(SyntaxKind.PublicKeyword),
									Token(SyntaxKind.StaticKeyword)))
								.AddMembers(members.ToArray())))
				.NormalizeWhitespace(eol: "\n");

			spc.AddSource("EntryKeys.g.cs",
				SourceText.From(cu.ToFullString(), Encoding.UTF8));
		});
	}
}
