using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DataCatalyst.V2;

[Generator]
public sealed class FluentAPIGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var source = @"// <auto-generated/>
namespace DataCatalyst.Generated
{
    public static class WorldExtensions
    {
        // Fluent API extensions generated at compile-time
    }
}";
            ctx.AddSource("FluentAPI.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}
