namespace DataCatalyst;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class PluginGenerator : IIncrementalGenerator {
	private const string PluginIface = "DataCatalyst.Abstractions.IPlugin";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var plugins = context.SyntaxProvider.CreateSyntaxProvider(
			predicate: static (node, _) => node is ClassDeclarationSyntax,
			transform: static (ctx, _) => {
				var t = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
				if (t == null) return default(PluginInfo?);

				var iface = ctx.SemanticModel.Compilation.GetTypeByMetadataName(PluginIface);
				if (iface == null || !t.AllInterfaces.Contains(iface, SymbolEqualityComparer.Default))
					return default(PluginInfo?);

				if (t.IsAbstract) return default(PluginInfo?);

				return new PluginInfo(
					t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
			})
			.Where(static p => p is not null)
			.Select(static (p, _) => p!.Value)
			.Collect();

		var config = ConfigHelper.GetConfig(context);
		var combined = plugins.Combine(config);

		context.RegisterSourceOutput(combined,
			static (spc, data) => {
				var (pl, cfg) = data;
				if (pl.Length == 0) return;
				Emit(spc, pl, cfg);
			});
	}

	private readonly struct PluginInfo(string fullType) {
		public readonly string FullType = fullType;
	}

	private static void Emit(SourceProductionContext spc, ImmutableArray<PluginInfo> allPlugins,
		AssemblyConfig config) {
		var initBody = new List<StatementSyntax>();
		var regBody = new List<StatementSyntax>();

		foreach (var p in allPlugins) {
			initBody.Add(BuildRegisterCall("global::DataCatalyst.Core.PluginRegistry.Default", p.FullType));
			regBody.Add(BuildGenericCall("registry", "RegisterPlugin", p.FullType));
		}

		initBody.Add(
			ExpressionStatement(
				InvocationExpression(
					MemberAccessExpression(
						SyntaxKind.SimpleMemberAccessExpression,
						ParseExpression("global::DataCatalyst.Core.PluginRegistry.Default"),
						IdentifierName("LoadAll")))));

		var ns = config.Namespace;
		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"));

		cu = cu.AddMembers(
				NamespaceDeclaration(IdentifierName(ns))
					.AddMembers(
						ClassDeclaration("PluginRegistrations")
							.WithModifiers(TokenList(
								Token(SyntaxKind.PublicKeyword),
								Token(SyntaxKind.StaticKeyword),
								Token(SyntaxKind.PartialKeyword)))
							.AddMembers(
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("Init"))
									.WithAttributeLists(
										SingletonList(
											AttributeList(
												SingletonSeparatedList(
													Attribute(
														ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
									.WithModifiers(TokenList(
										Token(SyntaxKind.InternalKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithBody(Block(initBody)),
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("RegisterTo"))
									.WithModifiers(TokenList(
										Token(SyntaxKind.PublicKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithParameterList(
										ParameterList(
											SingletonSeparatedList(
												Parameter(Identifier("registry"))
													.WithType(
														ParseTypeName("global::DataCatalyst.Core.DataRegistry")))))
									.WithBody(Block(regBody))))
					)
			.NormalizeWhitespace();

		spc.AddSource("PluginRegistrations.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static StatementSyntax BuildRegisterCall(string target, string fullType) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(target),
					GenericName("Register")
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));

	private static StatementSyntax BuildGenericCall(string instance, string method, string fullType) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(instance),
					GenericName(method)
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));
}
