namespace DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class PluginGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor CycleError = new(
		id: "DC003",
		title: "Circular plugin dependency",
		messageFormat: "Circular dependency detected involving plugin '{0}'",
		category: "DataCatalyst",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor UnknownDepWarning = new(
		id: "DC004",
		title: "Unknown plugin dependency",
		messageFormat: "Plugin '{0}' depends on '{1}' which is not a [DataPlugin] in this assembly",
		category: "DataCatalyst",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	private const string DataPluginAttr = "DataCatalyst.Abstractions.DataPluginAttribute";
	private const string DataPluginIface = "DataCatalyst.Abstractions.IDataPlugin";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var plugins = context.SyntaxProvider.ForAttributeWithMetadataName(
			DataPluginAttr,
			static (node, _) => node is ClassDeclarationSyntax,
			static (ctx, _) => {
				var t = (INamedTypeSymbol)ctx.TargetSymbol;
				var comp = ctx.SemanticModel.Compilation;
				var iface = comp.GetTypeByMetadataName(DataPluginIface);
				if (iface == null || !t.AllInterfaces.Contains(iface, SymbolEqualityComparer.Default))
					return default(PluginInfo?);
				var attrClass = comp.GetTypeByMetadataName(DataPluginAttr);
				var deps = GetDeps(t.GetAttributes(), attrClass);
				return new PluginInfo(t, deps);
			})
			.Where(static p => p is not null)
			.Select(static (p, _) => p!.Value)
			.Collect();

		context.RegisterSourceOutput(plugins,
			static (spc, pl) => {
				if (pl.Length == 0) return;
				Emit(spc, pl);
			});
	}

	private readonly struct PluginInfo {
		public readonly INamedTypeSymbol Type;
		public readonly string FullType;
		public readonly string[] Deps;

		public PluginInfo(INamedTypeSymbol type, string[] deps) {
			Type = type;
			FullType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			Deps = deps;
		}
	}

	private static string[] GetDeps(ImmutableArray<AttributeData> attrs, INamedTypeSymbol? attrClass) {
		if (attrClass == null) return [];

		foreach (var a in attrs) {
			if (!SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrClass)) continue;

			// Named argument: DependsOn
			foreach (var n in a.NamedArguments) {
				if (n.Key == "DependsOn" && n.Value.Values is { Length: > 0 } vs) {
					return vs
						.Select(v => v.Value)
						.OfType<INamedTypeSymbol>()
						.Select(s => s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
						.ToArray();
				}
			}

			// Positional constructor argument (also supports future constructor-based extension)
			if (a.ConstructorArguments.Length > 0) {
				var arg = a.ConstructorArguments[0];
				if (arg.Kind == TypedConstantKind.Array && arg.Values.Length > 0) {
					return arg.Values
						.Select(v => v.Value)
						.OfType<INamedTypeSymbol>()
						.Select(s => s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
						.ToArray();
				}
			}
		}
		return [];
	}

	private static void Emit(SourceProductionContext spc, ImmutableArray<PluginInfo> allPlugins) {
		var sorted = TopoSort([.. allPlugins], spc);
		if (sorted == null) return; // Cycle detected → abort emit, error diagnostic already reported

		var initBody = new List<StatementSyntax>();
		var regBody = new List<StatementSyntax>();

		foreach (var p in sorted) {
			initBody.Add(BuildRegisterCall("global::DataCatalyst.Core.PluginRegistry.Default", p.FullType));
			regBody.Add(BuildGenericCall("registry", "RegisterPlugin", p.FullType));
		}

		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
			.AddMembers(
				NamespaceDeclaration(IdentifierName("DataCatalyst.Core"))
					.AddMembers(
						ClassDeclaration("PluginRegistrations")
							.WithModifiers(TokenList(
								Token(SyntaxKind.PublicKeyword),
								Token(SyntaxKind.StaticKeyword),
								Token(SyntaxKind.PartialKeyword)))
							.AddMembers(
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("Init"))
									.WithAttributeLists(
										SingletonList(
											AttributeList(
												SingletonSeparatedList(
													Attribute(
														ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
									.WithModifiers(TokenList(
										Token(SyntaxKind.InternalKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithBody(Block(initBody)),
								MethodDeclaration(
										PredefinedType(Token(SyntaxKind.VoidKeyword)),
										Identifier("RegisterTo"))
									.WithModifiers(TokenList(
										Token(SyntaxKind.PublicKeyword),
										Token(SyntaxKind.StaticKeyword)))
									.WithParameterList(
										ParameterList(
											SingletonSeparatedList(
												Parameter(Identifier("registry"))
													.WithType(
														ParseTypeName("global::DataCatalyst.Core.DataRegistry")))))
									.WithBody(Block(regBody))))
					)
			.NormalizeWhitespace();

		spc.AddSource("PluginRegistrations.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static StatementSyntax BuildRegisterCall(string target, string fullType) {
		return ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(target),
					GenericName("Register")
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));
	}

	private static StatementSyntax BuildGenericCall(string instance, string method, string fullType) {
		return ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression(instance),
					GenericName(method)
						.WithTypeArgumentList(
							TypeArgumentList(
								SingletonSeparatedList(ParseTypeName(fullType)))))));
	}

	// Deterministic Kahn topological sort using sorted ready set
	private static List<PluginInfo>? TopoSort(List<PluginInfo> plugins, SourceProductionContext spc) {
		var map = new Dictionary<string, PluginInfo>();
		var indeg = new Dictionary<string, int>();
		var edges = new Dictionary<string, List<string>>();
		var allTypes = new HashSet<string>();

		foreach (var p in plugins) {
			if (map.ContainsKey(p.FullType)) continue;
			map[p.FullType] = p;
			allTypes.Add(p.FullType);
			indeg[p.FullType] = 0;
			edges[p.FullType] = [];
		}

		foreach (var p in plugins) {
			foreach (var d in p.Deps) {
				if (allTypes.Contains(d)) {
					edges[d].Add(p.FullType);
					indeg[p.FullType]++;
				}
				else {
					spc.ReportDiagnostic(Diagnostic.Create(
						UnknownDepWarning, Location.None, p.FullType, d));
				}
			}
		}

		// Use sorted list for deterministic ordering between builds
		var ready = allTypes.Where(t => indeg[t] == 0).ToList();
		ready.Sort();

		var result = new List<PluginInfo>();
		while (ready.Count > 0) {
			var cur = ready[0];
			ready.RemoveAt(0);
			result.Add(map[cur]);
			if (edges.TryGetValue(cur, out var list)) {
				foreach (var c in list) {
					if (--indeg[c] == 0) {
						ready.Add(c);
						ready.Sort();
					}
				}
			}
		}

		// Hard-fail on cycles: error diagnostic + abort emit
		var processed = new HashSet<string>(result.Select(p => p.FullType));
		if (processed.Count != allTypes.Count) {
			foreach (var t in allTypes) {
				if (!processed.Contains(t))
					spc.ReportDiagnostic(Diagnostic.Create(CycleError, Location.None, t));
			}
			return null;
		}

		return result;
	}
}
