namespace DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class PrimitiveDiscoveryGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static ctx =>
		{
			ctx.AddSource("DataPluginAttribute.g.cs", SourceText.From("""
				using System;

				[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
				public sealed class DataPluginAttribute : Attribute {
					public System.Type[]? DependsOn { get; init; }
				}
				""", Encoding.UTF8));
		});

		var plugins = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (node, _) => node is ClassDeclarationSyntax,
				static (ctx, _) => ExtractPlugin(ctx))
			.Where(static p => p is not null)
			.Select(static (p, _) => p!.Value)
			.Collect();

		var primitives = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (node, _) => node is TypeDeclarationSyntax,
				static (ctx, _) => ExtractPrimitive(ctx))
			.Where(static p => p is not null)
            .Select(static (p, _) => p!)
            .Collect();

        var combined = plugins.Combine(primitives);

		context.RegisterSourceOutput(combined, static (spc, payload) =>
		{
			var (pluginList, primitiveList) = payload;

			var sb = new StringBuilder();
			sb.Append("// <auto-generated/>\n#nullable enable\n\n");

			var hasPlugins = !pluginList.IsDefaultOrEmpty && pluginList.Length > 0;
			var hasPrimitives = !primitiveList.IsDefaultOrEmpty && primitiveList.Length > 0;

			if (!hasPlugins && !hasPrimitives) return;

			sb.Append("namespace DataCatalyst.Core {\n");
			sb.Append("\tpublic static partial class PrimitiveRegistrations {\n");

			if (hasPlugins)
			{
				var sorted = TopoSort(pluginList);
				sb.Append("\t\t[System.Runtime.CompilerServices.ModuleInitializer]\n");
				sb.Append("\t\tinternal static void Init() {\n");
				foreach (var (fullType, id, dependsOn) in sorted)
				{
					sb.Append("\t\t\tglobal::DataCatalyst.Core.PluginRegistry.Register<global::")
					  .Append(fullType).AppendLine(">();");
				}
				sb.Append("\t\t}\n");
			}

			if (hasPrimitives)
			{
				sb.Append("\n\t\t[System.Runtime.CompilerServices.ModuleInitializer]\n");
				sb.Append("\t\tinternal static void RegisterPrimitives() {\n");
				foreach (var fullType in primitiveList)
				{
					sb.Append("\t\t\tglobal::DataCatalyst.Core.PrimitiveRegistry.Register<global::")
					  .Append(fullType).AppendLine(">();");
				}
				sb.Append("\t\t}\n");
			}

			sb.Append("\t}\n}");
			spc.AddSource("PrimitiveRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}

	private static (string FullType, string Id, string[] DependsOn)? ExtractPlugin(GeneratorSyntaxContext ctx)
	{
		if (ctx.Node is not ClassDeclarationSyntax cds) return null;
		var model = ctx.SemanticModel;
		var type = model.GetDeclaredSymbol(cds) as INamedTypeSymbol;
		if (type is null) return null;
		if (!type.AllInterfaces.Any(i => i.Name == "IDataPlugin")) return null;

		string id = type.Name;
		string[] dependsOn = [];

		foreach (var attr in type.GetAttributes())
		{
			if (attr.AttributeClass?.Name != "DataPluginAttribute") continue;
			foreach (var na in attr.NamedArguments)
			{
				if (na.Key == "DependsOn" && na.Value.Values is { Length: > 0 } vs)
				{
					var list = new List<string>();
					foreach (var v in vs)
					{
						if (v.Value is INamedTypeSymbol depType && !string.IsNullOrEmpty(depType.Name))
							list.Add(depType.Name);
					}
					dependsOn = [.. list];
				}
			}
			break;
		}

		var fullType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		return (fullType, id, dependsOn);
	}

	private static string? ExtractPrimitive(GeneratorSyntaxContext ctx)
	{
		if (ctx.Node is not TypeDeclarationSyntax tds) return null;
		var model = ctx.SemanticModel;
		var type = model.GetDeclaredSymbol(tds) as INamedTypeSymbol;
		if (type is null) return null;

		foreach (var attr in type.GetAttributes())
		{
			if (attr.AttributeClass?.Name == "DataPrimitiveAttribute")
			{
				return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			}
		}
		return null;
	}

	private static (string FullType, string Id, string[] DependsOn)[] TopoSort(
		ImmutableArray<(string FullType, string Id, string[] DependsOn)> plugins)
	{
		var map = new Dictionary<string, (string FullType, string Id, string[] DependsOn)>();
		var indegree = new Dictionary<string, int>();
		var edges = new Dictionary<string, List<string>>();

		foreach (var p in plugins) { map[p.Id] = p; indegree[p.Id] = 0; edges[p.Id] = []; }
		foreach (var p in plugins)
			foreach (var dep in p.DependsOn)
				if (map.ContainsKey(dep)) { edges[dep].Add(p.Id); indegree[p.Id]++; }

		var ready = new List<(string FullType, string Id, string[] DependsOn)>();
		foreach (var p in plugins)
			if (!indegree.TryGetValue(p.Id, out var deg) || deg == 0) ready.Add(p);

		var sorted = new List<(string FullType, string Id, string[] DependsOn)>();
		while (ready.Count > 0)
		{
			var cur = ready[0]; ready.RemoveAt(0); sorted.Add(cur);
			foreach (var child in edges.TryGetValue(cur.Id, out var l) ? l : [])
			{
				indegree[child]--;
				if (indegree[child] == 0 && map.TryGetValue(child, out var n)) ready.Add(n);
			}
		}
		foreach (var p in plugins) if (!sorted.Contains(p)) sorted.Add(p);
		return [.. sorted];
	}
}
