namespace DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class PrimitiveDiscoveryGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor StructRecommendedWarning = new(
		id: "DC001",
		title: "DataComponent should be a struct",
		messageFormat: "[DataComponent] on '{0}' should be a struct for optimal AOT compatibility",
		category: "DataCatalyst",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var plugins = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (n, _) => n is ClassDeclarationSyntax,
				static (ctx, _) => ExtractPlugin(ctx))
			.Where(static p => p is not null)
			.Select(static (p, _) => p!.Value)
			.Collect();

		var primitives = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (n, _) => n is TypeDeclarationSyntax,
				static (ctx, _) => ExtractPrimitive(ctx))
			.Collect();

		context.RegisterSourceOutput(
			context.CompilationProvider.Combine(plugins).Combine(primitives),
			static (spc, payload) => {
				var ((comp, pl), pr) = payload;
				foreach (var p in pr) {
					if (p.Warning is {} w) {
						spc.ReportDiagnostic(Diagnostic.Create(StructRecommendedWarning, w));
					}
				}
				var prims = pr
					.Where(static p => p.FullType is not null)
					.Select(static p => (FullType: p.FullType!, ShortName: p.ShortName!))
					.ToImmutableArray();
				Emit(spc, comp, pl, prims);
			});
	}

	private static (string FullType, string Id, string[] Deps)? ExtractPlugin(GeneratorSyntaxContext ctx) {
		if (ctx.Node is not ClassDeclarationSyntax cds) {
			return null;
		}

		if (ctx.SemanticModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol t) {
			return null;
		}

		if (!t.AllInterfaces.Any(i => i.Name == "IDataPlugin")) {
			return null;
		}

		if (!HasAttr(t.GetAttributes(), "DataPluginAttribute")) {
			return null;
		}

		return (t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), t.Name, GetDeps(t.GetAttributes()));
	}

	private static PrimitiveResult ExtractPrimitive(GeneratorSyntaxContext ctx) {
		if (ctx.Node is not TypeDeclarationSyntax tds) {
			return default;
		}

		if (ctx.SemanticModel.GetDeclaredSymbol(tds) is not INamedTypeSymbol t) {
			return default;
		}

		if (!HasAttr(t.GetAttributes(), "DataComponentAttribute")) {
			return default;
		}

		Location? warning = t.TypeKind != TypeKind.Structure ? tds.GetLocation() : null;

		return new PrimitiveResult(
			t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
			t.Name,
			warning);
	}

	private readonly struct PrimitiveResult {
		public readonly string? FullType;
		public readonly string? ShortName;
		public readonly Location? Warning;

		public PrimitiveResult(string? fullType, string? shortName, Location? warning) {
			FullType = fullType;
			ShortName = shortName;
			Warning = warning;
		}
	}

	private static bool HasAttr(ImmutableArray<AttributeData> attrs, string name) {
		foreach (var a in attrs) {
			if (a.AttributeClass?.Name == name) {
				return true;
			}
		}

		return false;
	}

	private static string[] GetDeps(ImmutableArray<AttributeData> attrs) {
		foreach (var a in attrs) {
			if (a.AttributeClass?.Name != "DataPluginAttribute") {
				continue;
			}

			foreach (var n in a.NamedArguments) {
				if (n.Key == "DependsOn" && n.Value.Values is { Length: > 0 } vs) {
					var list = new List<string>();
					foreach (var v in vs) {
						if (v.Value is INamedTypeSymbol dt) {
							list.Add(dt.Name);
						}
					}

					return [.. list];
				}
			}
		}

		return [];
	}

	private static void Emit(SourceProductionContext spc, Compilation comp,
		ImmutableArray<(string FullType, string Id, string[] Deps)> classPlugins,
		ImmutableArray<(string FullType, string ShortName)> classPrims) {
		var allPlugins = new List<(string FullType, string Id, string[] Deps)>();
		var allPrims = new List<(string FullType, string ShortName)>();

		if (!classPlugins.IsDefaultOrEmpty) {
			allPlugins.AddRange(classPlugins);
		}

		if (!classPrims.IsDefaultOrEmpty) {
			allPrims.AddRange(classPrims);
		}

		// Scan referenced assemblies for IDataPlugin + [DataPlugin] + [DataComponent]
		foreach (var r in comp.References) {
			if (comp.GetAssemblyOrModuleSymbol(r) is not IAssemblySymbol asm) {
				continue;
			}

			ScanAssembly(asm, allPlugins, allPrims);
		}

		if (allPlugins.Count == 0 && allPrims.Count == 0) {
			return;
		}

		var sb = new StringBuilder();
		sb.Append("// <auto-generated/>\n#nullable enable\n\nnamespace DataCatalyst.Core {\n");
		sb.Append("\tpublic static partial class PrimitiveRegistrations {\n");

		sb.Append("\t\t[System.Runtime.CompilerServices.ModuleInitializer]\n");
		sb.Append("\t\tinternal static void Init() {\n");

		if (allPlugins.Count > 0) {
			var sorted = TopoSort(allPlugins);
			foreach (var (ft, _, _) in sorted) {
				sb.Append("\t\t\tglobal::DataCatalyst.Core.PluginRegistry.Register<")
					.Append(ft).AppendLine(">();");
			}
		}

		if (allPrims.Count > 0) {
			foreach (var (ft, _) in allPrims) {
				sb.Append("\t\t\tglobal::DataCatalyst.Core.PrimitiveRegistry.Register<")
					.Append(ft).AppendLine(">();");
			}

			sb.AppendLine();
			sb.Append("\t\t\tglobal::DataCatalyst.Core.PrimitiveRegistry.RegisterIds(new() {\n");
			foreach (var (ft, sn) in allPrims) {
				sb.Append("\t\t\t\t{ \"").Append(sn).Append("\", typeof(").Append(ft).Append(") },")
					.Append(" // ").AppendLine(sn);
			}
			sb.Append("\t\t\t});\n");
		}

		sb.Append("\t\t}\n");

		sb.Append("\n\t\tpublic static void RegisterTo(global::DataCatalyst.Core.DataRegistry registry) {\n");
		if (allPlugins.Count > 0) {
			var sorted = TopoSort(allPlugins);
			foreach (var (ft, _, _) in sorted) {
				sb.Append("\t\t\tregistry.RegisterPlugin<")
					.Append(ft).AppendLine(">();");
			}
		}

		if (allPrims.Count > 0) {
			foreach (var (ft, _) in allPrims) {
				sb.Append("\t\t\tregistry.RegisterComponent<")
					.Append(ft).AppendLine(">();");
			}
		}

		sb.Append("\t\t}\n");

		sb.Append("\t}\n}");
		spc.AddSource("PrimitiveRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
	}

	private static void ScanAssembly(IAssemblySymbol asm, List<(string, string, string[])> plugins,
		List<(string FullType, string ShortName)> prims) {
		foreach (var type in GetAllTypes(asm.GlobalNamespace)) {
			if (type.TypeKind != TypeKind.Class) {
				continue;
			}

			if (type.AllInterfaces.Any(i => i.Name == "IDataPlugin") &&
				HasAttr(type.GetAttributes(), "DataPluginAttribute")) {
				var ft = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				if (!plugins.Any(p => p.Item1 == ft)) {
					plugins.Add((ft, type.Name, GetDeps(type.GetAttributes())));
				}
			}
		}

		foreach (var type in GetAllTypes(asm.GlobalNamespace)) {
			if (type.TypeKind != TypeKind.Structure && type.TypeKind != TypeKind.Class) {
				continue;
			}

			if (!HasAttr(type.GetAttributes(), "DataComponentAttribute")) {
				continue;
			}

			var ft = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			if (prims.Any(p => p.FullType == ft)) {
				continue;
			}

			prims.Add((ft, type.Name));
		}
	}

	private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns) {
		foreach (var t in ns.GetTypeMembers()) {
			yield return t;
		}

		foreach (var c in ns.GetNamespaceMembers()) {
			foreach (var t in GetAllTypes(c)) {
				yield return t;
			}
		}
	}

	private static (string, string, string[])[] TopoSort(List<(string, string, string[])> plugins) {
		var map = new Dictionary<string, (string, string, string[])>();
		var indeg = new Dictionary<string, int>();
		var edges = new Dictionary<string, List<string>>();

		foreach (var p in plugins) {
			map[p.Item2] = p;
			indeg[p.Item2] = 0;
			edges[p.Item2] = [];
		}

		foreach (var (_, id, deps) in plugins) {
			foreach (var d in deps) {
				if (map.ContainsKey(d)) {
					edges[d].Add(id);
					indeg[id]++;
				}
			}
		}

		var ready = new List<(string, string, string[])>();
		foreach (var p in plugins) {
			if (indeg.TryGetValue(p.Item2, out var d) && d == 0) {
				ready.Add(p);
			}
		}

		var result = new List<(string, string, string[])>();
		while (ready.Count > 0) {
			var cur = ready[0];
			ready.RemoveAt(0);
			result.Add(cur);
			foreach (var c in edges.TryGetValue(cur.Item2, out var l) ? l : []) {
				if (--indeg[c] == 0 && map.TryGetValue(c, out var n)) {
					ready.Add(n);
				}
			}
		}

		foreach (var p in plugins) {
			if (!result.Contains(p)) {
				result.Add(p);
			}
		}

		return [.. result];
	}
}
