using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace DataCatalyst.V2;

[Generator]
public sealed class RegistryGenerator : IIncrementalGenerator
{
    private const string GameConceptAttr = "DataCatalyst.Attributes.GameConceptAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var concepts = context.SyntaxProvider.ForAttributeWithMetadataName(
            GameConceptAttr,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) =>
            {
                var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                return new ConceptInfo(
                    typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    typeSymbol.Name);
            }).Collect();

        context.RegisterSourceOutput(concepts, static (spc, list) =>
        {
            if (list.Length == 0) return;

            // Generate EntryRegistry with concept metadata
            var members = new List<MemberDeclarationSyntax>();

            foreach (var c in list)
            {
                var prop = ParseMemberDeclaration(
                    $"public static readonly string {c.ShortName} = \"{c.ShortName}\";"
                );
                if (prop != null) members.Add((MemberDeclarationSyntax)prop);
            }

            var classDecl = ClassDeclaration("ConceptNames")
                .WithModifiers(TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.StaticKeyword)))
                .WithMembers(List(members));

            var nsDecl = NamespaceDeclaration(ParseName("DataCatalyst.Generated"))
                .AddMembers(classDecl);

            var cu = CompilationUnit()
                .WithLeadingTrivia(Comment("// <auto-generated/>"))
                .WithMembers(SingletonList<MemberDeclarationSyntax>(nsDecl))
                .NormalizeWhitespace();

            spc.AddSource("ConceptNames.g.cs", SourceText.From(cu.ToFullString(), Encoding.UTF8));
        });
    }

    private readonly record struct ConceptInfo(string FullType, string ShortName);
}
