namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;

[DcPlugin(typeof(ITypeEmitter))]
public sealed class ModOverlayDataEmitter : ITypeEmitter {
	[ModuleInitializer]
	internal static void Register() => DcPluginRegistry.RegisterCompanion(new ModOverlayDataEmitter());

	public string Name => "ModOverlay";

	public bool Applies(DcGenerationContext ctx) => ctx.ModSupport;

	public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var ns = ctx.ContainingNamespace;
		if (!string.IsNullOrEmpty(ns)) {
			sb.Append("namespace ").Append(ns).AppendLine(";");
			sb.AppendLine();
		}

		var typeName = ctx.SimpleName;
		var enumName = typeName + "Kind";

		sb.Append("public static partial class ").Append(typeName).AppendLine("Mod {");
		sb.AppendLine("\tprivate static global::System.Collections.Generic.Dictionary<string, " + typeName + ">? _modEntries;");
		sb.AppendLine();

		EmitAddEntry(sb, typeName);
		sb.AppendLine();
		EmitRemoveEntry(sb, typeName);
		sb.AppendLine();
		EmitClear(sb, typeName);
		sb.AppendLine();
		EmitLoadMods(sb, typeName);
		sb.AppendLine();
		EmitGetByKind(sb, typeName, enumName);
		sb.AppendLine();
		EmitTryGetByName(sb, typeName, enumName);
		sb.AppendLine();
		EmitGetAllModEntries(sb, typeName);
		sb.AppendLine();
		EmitKindToString(sb, rows, enumName);

		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void EmitAdapterNotify(StringBuilder sb, string typeName, string method, string arg) {
		sb.AppendLine("\t\tforeach (var a in global::FM39hz.DataCatalyst.Runtime.DataViewAdapterRegistry.GetAdapters<" + typeName + ">())");
		sb.AppendLine("\t\t\ta." + method + "(" + arg + ");");
	}

	private static void EmitAddEntry(StringBuilder sb, string typeName) {
		sb.AppendLine("\tpublic static void AddEntry(string key, " + typeName + " entry) {");
		sb.AppendLine("\t\t_modEntries ??= new global::System.Collections.Generic.Dictionary<string, " + typeName + ">();");
		sb.AppendLine("\t\t_modEntries[key] = entry;");
		EmitAdapterNotify(sb, typeName, "OnEntryAdded", "key, entry");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\tpublic static void AddRange(params (string Key, " + typeName + " Value)[] entries) {");
		sb.AppendLine("\t\tif (entries is null) return;");
		sb.AppendLine("\t\tfor (var i = 0; i < entries.Length; i++) {");
		sb.AppendLine("\t\t\tAddEntry(entries[i].Key, entries[i].Value);");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private static void EmitRemoveEntry(StringBuilder sb, string typeName) {
		sb.AppendLine("\tpublic static void RemoveEntry(string key) {");
		sb.AppendLine("\t\tif (_modEntries?.Remove(key, out var old) == true) {");
		EmitAdapterNotify(sb, typeName, "OnEntryRemoved", "key");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private static void EmitClear(StringBuilder sb, string typeName) {
		sb.AppendLine("\tpublic static void Clear() {");
		sb.AppendLine("\t\t_modEntries?.Clear();");
		EmitAdapterNotify(sb, typeName, "OnAllCleared", "");
		sb.AppendLine("\t}");
	}

	private static void EmitLoadMods(StringBuilder sb, string typeName) {
		sb.AppendLine("\tpublic static void LoadMods(string modDir) {");
		sb.AppendLine("\t\tforeach (var file in global::System.IO.Directory.EnumerateFiles(modDir, \"*.json\")) {");
		sb.AppendLine("\t\t\tvar items = " + typeName + "Json.LoadAll(file);");
		sb.AppendLine("\t\t\tforeach (var item in items) {");
		sb.AppendLine("\t\t\t\tAddEntry(KindToString(item.Kind), item);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t\tforeach (var dslReader in global::FM39hz.DataCatalyst.Runtime.DslReaderRegistry.GetReaders<" + typeName + ">()) {");
		sb.AppendLine("\t\t\tforeach (var file in global::System.IO.Directory.EnumerateFiles(modDir, \"*\" + dslReader.FileExtension)) {");
		sb.AppendLine("\t\t\t\tvar text = global::System.IO.File.ReadAllText(file);");
		sb.AppendLine("\t\t\t\tif (dslReader.TryRead(text, out var item)) {");
		sb.AppendLine("\t\t\t\t\tAddEntry(KindToString(item.Kind), item);");
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private static void EmitGetByKind(StringBuilder sb, string typeName, string enumName) {
		sb.AppendLine("\tpublic static " + typeName + " Get(" + enumName + " kind) {");
		sb.AppendLine("\t\tvar key = KindToString(kind);");
		sb.AppendLine("\t\tif (_modEntries?.TryGetValue(key, out var mod) == true) return mod;");
		sb.AppendLine("\t\treturn " + typeName + ".Get(kind);");
		sb.AppendLine("\t}");
	}

	private static void EmitTryGetByName(StringBuilder sb, string typeName, string enumName) {
		sb.AppendLine("\tinternal static bool TryGet(string name, out " + typeName + " value) {");
		sb.AppendLine("\t\tif (_modEntries?.TryGetValue(name, out value) == true) return true;");
		sb.AppendLine("\t\tvalue = default!;");
		sb.AppendLine("\t\treturn false;");
		sb.AppendLine("\t}");
	}

	private static void EmitGetAllModEntries(StringBuilder sb, string typeName) {
		sb.AppendLine("\tpublic static global::System.Collections.Generic.IEnumerable<" + typeName + "> GetAllModEntries() {");
		sb.AppendLine("\t\tif (_modEntries is null) return global::System.Array.Empty<" + typeName + ">();");
		sb.AppendLine("\t\treturn _modEntries.Values;");
		sb.AppendLine("\t}");
	}

	private static void EmitKindToString(StringBuilder sb, IReadOnlyList<RowData> rows, string enumName) {
		sb.AppendLine("\tinternal static string KindToString(" + enumName + " kind) {");
		sb.AppendLine("\t\tswitch (kind) {");
		foreach (var row in rows) {
			sb.Append("\t\t\tcase ").Append(enumName).Append(".").Append(row.Key).Append(": return \"").Append(EscapeString(row.Key)).AppendLine("\";");
		}

		sb.AppendLine("\t\t\tdefault: throw new global::System.ArgumentException($\"Unknown '").Append(enumName).AppendLine("' value: {kind}\");");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private static string EscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
