namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;
using Microsoft.CodeAnalysis;

/// <summary>
///     Default DataCatalyst type emitter. Produces a partial type that exposes:
///     <list type="bullet">
///         <item>An enum <c>{TypeName}Kind</c> whose members are the row keys.</item>
///         <item>A <c>public static readonly</c> field per row.</item>
///         <item>An <c>All</c> <see cref="System.Collections.Frozen.FrozenDictionary{TKey, TValue}" /> for O(1) lookup.</item>
///         <item><c>Get</c> / <c>TryGet</c> helpers.</item>
///     </list>
///     <para>
///         <b>Breaking change vs. Wave 2:</b> if any column produces the C# member name <c>Kind</c>,
///         emission aborts with <see cref="DcDiagnostics.KindColumnCollision" />. The previous
///         auto-rename to <c>EnumKind</c> hid the conflict; consumers must now choose a domain term
///         (e.g. <c>Category</c>, <c>RuleKind</c>) for the JSON column.
///     </para>
/// </summary>
[DcPlugin(typeof(ITypeEmitter))]
internal sealed class PartialStructEmitter : ITypeEmitter {
	[ModuleInitializer]
	internal static void Register() => DcPluginRegistry.Register(new PartialStructEmitter());

	public string Name => "PartialStruct";

	public bool Applies(DcGenerationContext ctx) => true;

	public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
		foreach (var col in schema.Columns) {
			if (string.Equals(col.MemberName, "Kind", System.StringComparison.Ordinal)) {
				ctx.ReportDiagnostic(Diagnostic.Create(DcDiagnostics.KindColumnCollision, ctx.Location, ctx.TargetFullyQualifiedName));
				return string.Empty;
			}
		}

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var ns = ctx.ContainingNamespace;
		if (!string.IsNullOrEmpty(ns)) {
			sb.Append("namespace ").Append(ns).AppendLine(";");
			sb.AppendLine();
		}

		var enumName = ctx.SimpleName + "Kind";

		sb.AppendLine($"public enum {enumName} {{");
		for (var i = 0; i < rows.Count; i++) {
			sb.AppendLine($"\t{rows[i].Key} = {i.ToString(CultureInfo.InvariantCulture)},");
		}

		sb.AppendLine("}");
		sb.AppendLine();

		var keyword = TypeDeclarationKeyword(ctx);
		sb.Append("public partial ").Append(keyword).Append(' ').Append(ctx.SimpleName).AppendLine(" {");

		EmitNestedTypes(sb, schema.Columns, indent: 1);

		foreach (var col in schema.Columns) {
			sb.Append("\tpublic ");
			sb.Append(EmitFieldType(col.Type));
			sb.Append(' ');
			sb.Append(col.MemberName);
			sb.AppendLine(" { get; init; }");
		}

		sb.AppendLine();
		sb.Append("\tpublic ").Append(enumName).AppendLine(" Kind { get; init; }");

		sb.AppendLine();
		foreach (var row in rows) {
			sb.Append($"\tpublic static readonly {ctx.SimpleName} {row.Key} = new {ctx.SimpleName} {{");
			sb.AppendLine();
			sb.Append("\t\tKind = ").Append(enumName).Append('.').Append(row.Key).Append(',');
			sb.AppendLine();
			foreach (var col in schema.Columns) {
				sb.Append("\t\t").Append(col.MemberName).Append(" = ");
				sb.Append(EmitValue(col.Type, row.Values.TryGetValue(col.Name, out var v) ? v : null));
				sb.AppendLine(",");
			}

			sb.AppendLine("\t};");
		}

		sb.AppendLine();
		sb.AppendLine($"\tpublic static readonly global::System.Collections.Frozen.FrozenDictionary<{enumName}, {ctx.SimpleName}> All =");
		sb.AppendLine($"\t\tglobal::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(new global::System.Collections.Generic.Dictionary<{enumName}, {ctx.SimpleName}> {{");
		foreach (var row in rows) {
			sb.AppendLine($"\t\t\t{{ {enumName}.{row.Key}, {row.Key} }},");
		}

		sb.AppendLine("\t\t});");
		sb.AppendLine();
		sb.AppendLine($"\tpublic static readonly global::System.Collections.Frozen.FrozenDictionary<string, {enumName}> KindByName =");
		sb.AppendLine($"\t\tglobal::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(new global::System.Collections.Generic.Dictionary<string, {enumName}>(global::System.StringComparer.Ordinal) {{");
		foreach (var row in rows) {
			sb.AppendLine($"\t\t\t{{ {CodeEmitString(row.Key)}, {enumName}.{row.Key} }},");
		}
		sb.AppendLine("\t\t});");

		EmitAccessors(sb, ctx, rows, enumName);

		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void EmitAccessors(StringBuilder sb, DcGenerationContext ctx, IReadOnlyList<RowData> rows, string enumName) {
		var t = ctx.SimpleName;
		var hasBackend = ctx.Backend != DataBackend.None;
		var hasMods = ctx.ModSupport;

		sb.AppendLine();
		sb.AppendLine($"\tpublic static int Count => All.Count;");
		sb.AppendLine($"\tpublic static global::System.Collections.Generic.IEnumerable<{enumName}> Kinds => All.Keys;");
		sb.AppendLine($"\tpublic static global::System.Collections.Generic.IEnumerable<{t}> Values => All.Values;");
		sb.AppendLine();

		// Get(Kind) — type-safe, backend-aware, mod-aware
		if (hasBackend && hasMods) {
			sb.AppendLine($"\tpublic static {t} Get({enumName} kind) {{");
			sb.AppendLine($"\t\tif ({t}Mod.TryGet({t}Mod.KindToString(kind), out var m)) return m;");
			sb.AppendLine($"\t\tvar b = global::FM39hz.DataCatalyst.Runtime.DataBackendSelector.Current;");
			sb.AppendLine($"\t\tif (b != 0) return ResolveRepository().Get(kind);");
			sb.AppendLine($"\t\treturn All[kind];");
			sb.AppendLine("\t}");
		} else if (hasBackend) {
			sb.AppendLine($"\tpublic static {t} Get({enumName} kind) {{");
			sb.AppendLine($"\t\tvar b = global::FM39hz.DataCatalyst.Runtime.DataBackendSelector.Current;");
			sb.AppendLine($"\t\tif (b != 0) return ResolveRepository().Get(kind);");
			sb.AppendLine($"\t\treturn All[kind];");
			sb.AppendLine("\t}");
		} else if (hasMods) {
			sb.AppendLine($"\tpublic static {t} Get({enumName} kind) {{");
			sb.AppendLine($"\t\tif ({t}Mod.TryGet({t}Mod.KindToString(kind), out var m)) return m;");
			sb.AppendLine($"\t\treturn All[kind];");
			sb.AppendLine("\t}");
		} else {
			sb.AppendLine($"\tpublic static {t} Get({enumName} kind) => All[kind];");
		}

		// TryGet(Kind, out) — type-safe, backend-aware, mod-aware
		if (hasBackend && hasMods) {
			sb.AppendLine($"\tpublic static bool TryGet({enumName} kind, out {t} value) {{");
			sb.AppendLine($"\t\tif ({t}Mod.TryGet({t}Mod.KindToString(kind), out var m)) {{ value = m; return true; }}");
			sb.AppendLine($"\t\tvar b = global::FM39hz.DataCatalyst.Runtime.DataBackendSelector.Current;");
			sb.AppendLine($"\t\tif (b != 0) return ResolveRepository().TryGet(kind, out value);");
			sb.AppendLine($"\t\treturn All.TryGetValue(kind, out value!);");
			sb.AppendLine("\t}");
		} else if (hasBackend) {
			sb.AppendLine($"\tpublic static bool TryGet({enumName} kind, out {t} value) {{");
			sb.AppendLine($"\t\tvar b = global::FM39hz.DataCatalyst.Runtime.DataBackendSelector.Current;");
			sb.AppendLine($"\t\tif (b != 0) return ResolveRepository().TryGet(kind, out value);");
			sb.AppendLine($"\t\treturn All.TryGetValue(kind, out value!);");
			sb.AppendLine("\t}");
		} else if (hasMods) {
			sb.AppendLine($"\tpublic static bool TryGet({enumName} kind, out {t} value) {{");
			sb.AppendLine($"\t\tif ({t}Mod.TryGet({t}Mod.KindToString(kind), out var m)) {{ value = m; return true; }}");
			sb.AppendLine($"\t\treturn All.TryGetValue(kind, out value!);");
			sb.AppendLine("\t}");
		} else {
			sb.AppendLine($"\tpublic static bool TryGet({enumName} kind, out {t} value) => All.TryGetValue(kind, out value!);");
		}

		sb.AppendLine($"\tpublic static bool Contains({enumName} kind) => All.ContainsKey(kind);");
		sb.AppendLine();
		sb.AppendLine($"\tpublic static global::System.Collections.Generic.IEnumerable<{t}> Query(global::System.Func<{t}, bool> predicate) =>");
		sb.AppendLine($"\t\tglobal::System.Linq.Enumerable.Where(Values, predicate);");
		sb.AppendLine($"\tpublic static global::System.Collections.Generic.IEnumerable<{t}> Find(global::System.Func<{t}, bool> predicate) =>");
		sb.AppendLine($"\t\tglobal::System.Linq.Enumerable.Where(Values, predicate);");
		sb.AppendLine();

		// CatalogRegistry registration via [ModuleInitializer]
		sb.AppendLine("\t[global::System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("\tinternal static void RegisterCatalog() =>");
		sb.AppendLine("\t\tglobal::FM39hz.DataCatalyst.Runtime.CatalogRegistry.Register<" + t + ">();");
		sb.AppendLine();

		if (hasBackend) {
			sb.AppendLine();
			sb.AppendLine($"\tprivate sealed class Core{t}Repository : global::FM39hz.DataCatalyst.Runtime.IDataRepository<{enumName}, {t}> {{");
			sb.AppendLine($"\t\tpublic {t} Get({enumName} kind) => All[kind];");
			sb.AppendLine($"\t\tpublic bool TryGet({enumName} kind, out {t} value) => All.TryGetValue(kind, out value!);");
			sb.AppendLine($"\t\tpublic global::System.Collections.Generic.IEnumerable<{t}> GetAll() => Values;");
			sb.AppendLine($"\t\tpublic int Count => All.Count;");
			sb.AppendLine("\t}");
			sb.AppendLine();
			sb.AppendLine($"\tpublic static global::FM39hz.DataCatalyst.Runtime.IDataRepository<{enumName}, {t}> ResolveRepository() {{");
			sb.AppendLine($"\t\tvar backend = global::FM39hz.DataCatalyst.Runtime.DataBackendSelector.Current;");
			sb.AppendLine($"\t\tvar connStr = global::System.Environment.GetEnvironmentVariable(\"DATACATALYST_CONNECTION\");");
			sb.AppendLine($"\t\tvar dataPath = global::System.Environment.GetEnvironmentVariable(\"DATACATALYST_DATAPATH\");");
			sb.AppendLine($"\t\tif (backend.HasFlag(global::FM39hz.DataCatalyst.Abstractions.DataBackend.Sqlite)) {{");
			sb.AppendLine($"\t\t\treturn new {t}SqlRepository(() => new global::Microsoft.Data.Sqlite.SqliteConnection(connStr ?? \"{t}.db\"));");
			sb.AppendLine($"\t\t}}");
			sb.AppendLine($"\t\tif (backend.HasFlag(global::FM39hz.DataCatalyst.Abstractions.DataBackend.Json)) {{");
			sb.AppendLine($"\t\t\treturn new {t}JsonRepository(dataPath ?? \"{ctx.JsonPath}\");");
			sb.AppendLine($"\t\t}}");
			sb.AppendLine($"\t\treturn new Core{t}Repository();");
			sb.AppendLine("\t}");
		}
	}

	private static string TypeDeclarationKeyword(DcGenerationContext ctx) =>
		ctx.TypeKind switch {
			TypeKind.Class when ctx.IsRecord => "record",
			TypeKind.Class => "class",
			TypeKind.Struct when ctx.IsRecord => "record struct",
			TypeKind.Struct => "struct",
			TypeKind.Unknown => throw new System.NotImplementedException(),
			TypeKind.Array => throw new System.NotImplementedException(),
			TypeKind.Delegate => throw new System.NotImplementedException(),
			TypeKind.Dynamic => throw new System.NotImplementedException(),
			TypeKind.Enum => throw new System.NotImplementedException(),
			TypeKind.Error => throw new System.NotImplementedException(),
			TypeKind.Interface => throw new System.NotImplementedException(),
			TypeKind.Module => throw new System.NotImplementedException(),
			TypeKind.Pointer => throw new System.NotImplementedException(),
			TypeKind.TypeParameter => throw new System.NotImplementedException(),
			TypeKind.Submission => throw new System.NotImplementedException(),
			TypeKind.FunctionPointer => throw new System.NotImplementedException(),
			TypeKind.Extension => throw new System.NotImplementedException(),
			_ => "struct",
		};

	private static void EmitNestedTypes(StringBuilder sb, ImmutableArray<SchemaColumn> columns, int indent) {
		foreach (var col in columns) {
			if (col.Type.IsObject) {
				var ind = new string('\t', indent);
				sb.Append(ind).Append("public partial struct ").Append(NestedTypeName(col.MemberName)).AppendLine(" {");
				EmitNestedTypes(sb, col.Type.ObjectColumns, indent + 1);
				foreach (var member in col.Type.ObjectColumns) {
					sb.Append(ind).Append('\t').Append("public ").Append(EmitFieldType(member.Type)).Append(' ').Append(member.MemberName).AppendLine(" { get; init; }");
				}

				sb.Append(ind).AppendLine("}");
				sb.AppendLine();
			}
			else if (col.Type.IsArray && col.Type.ArrayElement!.IsObject) {
				EmitNestedTypes(sb, [new SchemaColumn(col.Name, col.Type.ArrayElement)], indent);
			}
		}
	}

	private static string NestedTypeName(string columnName) => columnName + "Row";

	private static string EmitFieldType(SchemaType type) {
		if (type.IsPrimitive) {
			return type.Primitive!;
		}

		if (type.IsArray) {
			return $"global::System.Collections.Immutable.ImmutableArray<{EmitFieldType(type.ArrayElement!)}>";
		}

		if (type.IsObject) {
			return NestedTypeName(type.OwningColumnName ?? "Nested");
		}

		return "object";
	}

	private static string EmitValue(SchemaType type, JsonValueModel? value) {
		if (value is null || value.Kind == JsonValueKind.Null || value.Kind == JsonValueKind.Undefined) {
			return EmitDefault(type);
		}

		if (type.IsPrimitive) {
			return EmitPrimitiveLiteral(type.Primitive!, value);
		}

		if (type.IsArray) {
			if (value.Kind != JsonValueKind.Array || value.ArrayItems is null) {
				return EmitDefault(type);
			}

			var sb = new StringBuilder();
			sb.Append($"global::System.Collections.Immutable.ImmutableArray.Create<{EmitFieldType(type.ArrayElement!)}>(");
			for (var i = 0; i < value.ArrayItems.Count; i++) {
				if (i > 0) {
					sb.Append(", ");
				}

				sb.Append(EmitValue(type.ArrayElement!, value.ArrayItems[i]));
			}

			sb.Append(")");
			return sb.ToString();
		}

		if (type.IsObject) {
			var nestedTypeName = NestedTypeName(type.OwningColumnName ?? "Nested");
			if (value.Kind != JsonValueKind.Object || value.ObjectMembers is null) {
				return $"new {nestedTypeName}()";
			}

			var sb = new StringBuilder();
			sb.Append($"new {nestedTypeName} {{ ");
			var first = true;
			foreach (var col in type.ObjectColumns) {
				if (!first) {
					sb.Append(", ");
				}

				first = false;
				value.ObjectMembers.TryGetValue(col.Name, out var member);
				sb.Append(col.MemberName).Append(" = ").Append(EmitValue(col.Type, member));
			}

			sb.Append(" }");
			return sb.ToString();
		}

		return "default!";
	}

	private static string EmitDefault(SchemaType type) {
		if (type.IsPrimitive) {
			foreach (var rule in DcPluginRegistry.Primitives) {
				if (rule.Name == type.Primitive) {
					return rule.EmitDefault();
				}
			}

			foreach (var rule in DcPluginRegistry.TemplateLiteralRules) {
				if (rule.CanEmitDefault(type.Primitive!)) {
					return rule.EmitDefault(type.Primitive!);
				}
			}

			return $"default({type.Primitive})";
		}

		if (type.IsArray) {
			return $"global::System.Collections.Immutable.ImmutableArray<{EmitFieldType(type.ArrayElement!)}>.Empty";
		}

		return "default!";
	}

	private static string EmitPrimitiveLiteral(string primitive, JsonValueModel value) {
		foreach (var rule in DcPluginRegistry.Primitives) {
			if (rule.Name == primitive) {
				return rule.EmitLiteral(value);
			}
		}

		foreach (var rule in DcPluginRegistry.TemplateLiteralRules) {
			if (rule.CanEmit(primitive, value)) {
				return rule.EmitLiteral(primitive, value);
			}
		}

		return $"default({primitive})";
	}

	private static string CodeEmitString(string value) =>
		"\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\0", "\\0") + "\"";
}
