namespace DataCatalyst.Plugins.StateEngine;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

[Generator]
public sealed class StateMachineGenerator : IIncrementalGenerator {
	private static readonly DiagnosticDescriptor EmptyEnumWarning = new(
		id: "DC021",
		title: "Enum has no members",
		messageFormat: "[DataConcept] on '{0}' enum has no members. Mapper will have no valid mappings.",
		category: "DataCatalyst.StateEngine",
		defaultSeverity: DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

	private const string DataConceptAttr = "DataCatalyst.Plugins.GameConcept.DataConceptAttribute";
	private const string SpecialEnumBackingField = "value__";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
			DataConceptAttr,
			static (node, _) => node is EnumDeclarationSyntax,
			static (ctx, _) => {
				var t = (INamedTypeSymbol)ctx.TargetSymbol;
				var members = t.GetMembers().OfType<IFieldSymbol>()
					.Where(f => f.ConstantValue != null && !f.Name.StartsWith(SpecialEnumBackingField))
					.Select(f => f.Name)
					.ToArray();
				var fullType = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				return new EnumInfo(fullType, GetShortName(fullType), members);
			}).Collect();

		context.RegisterSourceOutput(enums,
			static (spc, results) => {
				var valid = results.Where(r => r.Members.Length > 0).ToImmutableArray();
				if (valid.Length == 0) return;
				Emit(spc, valid);
			});
	}

	private readonly struct EnumInfo(string fullType, string shortName, string[] members) {
		public readonly string FullType = fullType;
		public readonly string ShortName = shortName;
		public readonly string[] Members = members;
	}

	private static void Emit(SourceProductionContext spc,
		ImmutableArray<EnumInfo> enums) {

		var members = new List<MemberDeclarationSyntax>();
		var initStatements = new List<StatementSyntax>();

		foreach (var info in enums) {
			members.Add(BuildStateMapper(info));
			members.Add(BuildSensorMapper(info));

			var stateIface = ParseTypeName($"global::DataCatalyst.Plugins.StateEngine.Contracts.IStateMapper<{info.FullType}>");
			var sensorIface = ParseTypeName($"global::DataCatalyst.Plugins.StateEngine.Contracts.ISensorMapper<{info.FullType}>");
			initStatements.Add(RegisterMapper(stateIface, $"{info.ShortName}StateMapper"));
			initStatements.Add(RegisterMapper(sensorIface, $"{info.ShortName}SensorMapper"));
		}

		members.Add(
			ClassDeclaration("StateEngineRegistrations")
				.WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword)))
				.AddMembers(
					MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), Identifier("Init"))
						.WithAttributeLists(SingletonList(AttributeList(SingletonSeparatedList(
							Attribute(ParseName("System.Runtime.CompilerServices.ModuleInitializer"))))))
						.WithModifiers(TokenList(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword)))
						.WithBody(Block(initStatements))));

		var cu = CompilationUnit()
			.WithLeadingTrivia(Comment("// <auto-generated/>\n#nullable enable"))
			.AddMembers(
				NamespaceDeclaration(IdentifierName("DataCatalyst.Plugins.StateEngine.Generated"))
					.AddMembers([.. members]))
			.NormalizeWhitespace(eol: "\n");

		spc.AddSource("StateMachineRegistrations.g.cs",
			SourceText.From(cu.ToFullString(), Encoding.UTF8));
	}

	private static StatementSyntax RegisterMapper(TypeSyntax interfaceType, string mapperType) => ExpressionStatement(
			InvocationExpression(
				MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression,
					ParseExpression("global::DataCatalyst.Core.MapperRegistry.Default"),
					GenericName("Register").WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList(interfaceType)))))
				.WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(
					ObjectCreationExpression(ParseTypeName(mapperType)).WithArgumentList(ArgumentList()))))));

	private static MemberDeclarationSyntax BuildStateMapper(EnumInfo info) {
		var className = $"{info.ShortName}StateMapper";
		var iface = ParseTypeName($"global::DataCatalyst.Plugins.StateEngine.Contracts.IStateMapper<{info.FullType}>");
		var retType = ParseTypeName(info.FullType);
		var switchArms = BuildSwitchArms(info, retType);
		switchArms.Add(DefaultSwitchSection(className, "name"));

		var body = new List<StatementSyntax>();
		// var dot = stateKey.IndexOf('.');
		body.Add(LocalDeclarationStatement(VariableDeclaration(IdentifierName("var"))
			.WithVariables(SingletonSeparatedList(VariableDeclarator(Identifier("dot"))
				.WithInitializer(EqualsValueClause(InvocationExpression(
					MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, IdentifierName("stateKey"), IdentifierName("IndexOf")))
					.WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(
						LiteralExpression(SyntaxKind.StringLiteralExpression, Literal("."))))))))))));
		// var name = dot >= 0 ? stateKey.Substring(dot + 1) : stateKey;
		body.Add(LocalDeclarationStatement(VariableDeclaration(IdentifierName("var"))
			.WithVariables(SingletonSeparatedList(VariableDeclarator(Identifier("name"))
				.WithInitializer(EqualsValueClause(ConditionalExpression(
					BinaryExpression(SyntaxKind.GreaterThanOrEqualExpression, IdentifierName("dot"),
						LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(0))),
					InvocationExpression(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
						IdentifierName("stateKey"), IdentifierName("Substring")))
						.WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(
							BinaryExpression(SyntaxKind.AddExpression, IdentifierName("dot"),
								LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(1))))))),
					IdentifierName("stateKey"))))))));
		body.Add(SwitchStatement(IdentifierName("name")).AddSections([.. switchArms]));

		return ClassDeclaration(className).WithModifiers(TokenList(Token(SyntaxKind.SealedKeyword)))
			.AddBaseListTypes(SimpleBaseType(iface))
			.AddMembers(MethodDeclaration(retType, Identifier("MapState"))
				.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
				.WithParameterList(ParameterList(SeparatedList([
					Parameter(Identifier("stateKey")).WithType(PredefinedType(Token(SyntaxKind.StringKeyword))),
					Parameter(Identifier("groupId")).WithType(PredefinedType(Token(SyntaxKind.StringKeyword)))
				])))
				.WithBody(Block(body)));
	}

	private static MemberDeclarationSyntax BuildSensorMapper(EnumInfo info) {
		var className = $"{info.ShortName}SensorMapper";
		var iface = ParseTypeName($"global::DataCatalyst.Plugins.StateEngine.Contracts.ISensorMapper<{info.FullType}>");
		var retType = ParseTypeName(info.FullType);
		var switchArms = BuildSwitchArms(info, retType);
		switchArms.Add(DefaultSwitchSection(className, "signal"));

		return ClassDeclaration(className).WithModifiers(TokenList(Token(SyntaxKind.SealedKeyword)))
			.AddBaseListTypes(SimpleBaseType(iface))
			.AddMembers(MethodDeclaration(retType, Identifier("MapSensor"))
				.WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
				.WithParameterList(ParameterList(SingletonSeparatedList(
					Parameter(Identifier("signal")).WithType(PredefinedType(Token(SyntaxKind.StringKeyword))))))
				.WithBody(Block(SingletonList<StatementSyntax>(SwitchStatement(IdentifierName("signal")).AddSections([.. switchArms])))));
	}

	private static List<SwitchSectionSyntax> BuildSwitchArms(EnumInfo info, TypeSyntax retType) {
		var arms = new List<SwitchSectionSyntax>();
		foreach (var m in info.Members) {
			arms.Add(SwitchSection().AddLabels(CaseSwitchLabel(LiteralExpression(
				SyntaxKind.StringLiteralExpression, Literal(m))))
				.AddStatements(ReturnStatement(MemberAccessExpression(
					SyntaxKind.SimpleMemberAccessExpression, retType, IdentifierName(m)))));
		}
		return arms;
	}

	private static SwitchSectionSyntax DefaultSwitchSection(string className, string varName) =>
		SwitchSection().AddLabels(DefaultSwitchLabel())
			.AddStatements(ThrowStatement(ObjectCreationExpression(ParseTypeName("global::System.ArgumentException"))
				.WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(BinaryExpression(
					SyntaxKind.AddExpression,
					BinaryExpression(SyntaxKind.AddExpression,
						LiteralExpression(SyntaxKind.StringLiteralExpression, Literal($"Unknown {className}: ")),
						IdentifierName(varName)),
					LiteralExpression(SyntaxKind.StringLiteralExpression, Literal("")))))))));

	private static string GetShortName(string fullType) {
		var name = fullType;
		if (name.StartsWith("global::")) name = name.Substring(8);
		var lastDot = name.LastIndexOf('.');
		return lastDot >= 0 ? name.Substring(lastDot + 1) : name;
	}
}
