namespace Catalyst.SourceGen.Generation;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Catalyst.SourceGen.Models;
using Microsoft.CodeAnalysis;

internal sealed class SourceEmitter {
    private readonly Dictionary<string, AspectInfo> _aspectDict;
    private readonly HashSet<string> _aspectNames;
    private readonly HashSet<string> _localAspectNames;
    private readonly Dictionary<string, string> _conceptNsMap;
    private readonly HashSet<string> _conceptNames;
    private readonly Dictionary<string, List<string>> _beingConcepts;
    private readonly Dictionary<string, HashSet<string>> _conceptAspects;
    private readonly List<AspectInfo?> _combinedAspects;
    private readonly Dictionary<string, string> _beingDescriptions;

    public SourceEmitter(
        Dictionary<string, AspectInfo> aspectDict,
        HashSet<string> aspectNames,
        HashSet<string> localAspectNames,
        Dictionary<string, string> conceptNsMap,
        HashSet<string> conceptNames,
        Dictionary<string, List<string>> beingConcepts,
        Dictionary<string, HashSet<string>> conceptAspects,
        List<AspectInfo?> combinedAspects,
        Dictionary<string, string>? beingDescriptions = null) {
        _aspectDict = aspectDict;
        _aspectNames = aspectNames;
        _localAspectNames = localAspectNames;
        _conceptNsMap = conceptNsMap;
        _conceptNames = conceptNames;
        _beingConcepts = beingConcepts;
        _conceptAspects = conceptAspects;
        _combinedAspects = combinedAspects;
        _beingDescriptions = beingDescriptions ?? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    }

    private static void XmlDoc(CodeWriter w, string? text) {
        if (string.IsNullOrEmpty(text)) return;
        w.Line("/// <summary>");
        w.Line($"/// {text}");
        w.Line("/// </summary>");
    }

    public string ConceptRef(string name) => _conceptNsMap.TryGetValue(name, out var ns)
        ? $"global::{ns}.{Helpers.Sanitize(name)}"
        : $"global::Catalyst.Generated.{Helpers.Sanitize(name)}";

    public void EmitConceptStructs(
        HashSet<string> allOntologyConcepts,
        bool hasOntology,
        Dictionary<string, string>? descriptions,
        CodeWriter writer,
        SourceProductionContext spc) {
        if (!hasOntology) return;
        writer.Line("#nullable enable");
        writer.Line("// <auto-generated/>");
        writer.Block("namespace Catalyst.Generated");
        foreach (var cn in allOntologyConcepts) {
            if (_conceptNames.Contains(cn)) continue;
            if (descriptions != null && descriptions.TryGetValue(cn, out var d))
                XmlDoc(writer, d);
            writer.Line($"public struct {Helpers.Sanitize(cn)} : global::Catalyst.IConcept {{ }}");
            _conceptNames.Add(cn);
            if (!_conceptNsMap.ContainsKey(cn)) _conceptNsMap[cn] = "Catalyst.Generated";
        }
        writer.EndBlock();
    }

    public void EmitOntologyAspects(
        Dictionary<string, Dictionary<string, string>> ontologyAspects,
        bool hasOntology,
        Dictionary<string, string>? descriptions,
        Dictionary<string, List<string>> aspectConcepts,
        CodeWriter writer,
        SourceProductionContext spc) {
        if (!hasOntology || ontologyAspects.Count == 0) return;
        writer.Line("#nullable enable");
        writer.Line("// <auto-generated/>");
        writer.Block("namespace Catalyst.Generated");
        foreach (var kv in ontologyAspects) {
            var aName = Helpers.Sanitize(kv.Key);
            if (_aspectDict.ContainsKey(kv.Key)) continue;
            if (descriptions != null && descriptions.TryGetValue(kv.Key, out var d))
                XmlDoc(writer, d);
            writer.Line("[global::Catalyst.Attributes.GameAspectAttribute]");

            // Add IRevealedBy<T> for each concept that reveals this aspect
            var ifaces = "";
            if (aspectConcepts.TryGetValue(kv.Key, out var concepts)) {
                ifaces = string.Join(", ", concepts.Select(c => $"global::Catalyst.IRevealedBy<{ConceptRef(c)}>"));
            }
            if (!string.IsNullOrEmpty(ifaces))
                writer.Line($"public struct {aName} : {ifaces}");
            else
                writer.Line($"public struct {aName}");
            writer.Line("{");
            writer.Indent();
            foreach (var field in kv.Value) {
                var fName = Helpers.Sanitize(field.Key);
                var fType = TypeMapping.MapTypeString(field.Value);
                writer.Line($"public {fType} {fName} {{ get; set; }}");
            }
            writer.Unindent();
            writer.Line("}");
            _aspectDict[kv.Key] = new AspectInfo(kv.Key, "Catalyst.Generated",
                string.Join(";", kv.Value.Select(f => $"{f.Key}:{TypeMapping.MapTypeString(f.Value)}")));
            _localAspectNames.Add(kv.Key);
            _aspectNames.Add(kv.Key);
        }
        writer.EndBlock();
    }

    public void EmitDeserializerHelpers(
        Dictionary<string, List<string>> ontologyRequires,
        Dictionary<string, List<string>> ontologySuggests,
        HashSet<string> allOntologyConcepts,
        bool hasOntology,
        CodeWriter writer,
        SourceProductionContext spc) {
        bool hasDeser = false;
        foreach (var a in _combinedAspects) { if (a != null) { hasDeser = true; break; } }
        bool hasPoolReg = false;
        foreach (var kv in _conceptAspects) {
            if (_conceptNames.Contains(kv.Key)) { hasPoolReg = true; break; }
        }
        if (!hasDeser && _beingConcepts.Count == 0 && !hasPoolReg && !hasOntology) return;

        writer.Line("#nullable enable");
        writer.Line("// <auto-generated/>");
        writer.Block("namespace Catalyst.Generated");
        writer.Block("public static class CatalystRegistries");

        // ── Deserializer helper methods ──
        int deserIdx = 0;
        foreach (var asp in _combinedAspects) {
            if (asp == null) continue;
            var nm = Helpers.Sanitize(asp.Name);
            var fullTypeName = $"global::{asp.Namespace}.{nm}";
            var propParts = asp.PropertiesString.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
            var setters = new List<string>();
            foreach (var part in propParts) {
                var (pName, pType) = ParsePropertyDef(part);
                if (pName == null || pType == null) continue;
                var sn = Helpers.Sanitize(pName);
                var defVal = IsKnownValueType(pType) || pType.EndsWith("?") ? $"default({pType})" : $"default({pType})!";
                setters.Add($"{sn} = __dict.TryGetValue(\"{pName}\", out var __v{deserIdx}_{pName}) && __v{deserIdx}_{pName} != null ? {TypeMapping.Cast(pType, "__v" + deserIdx + "_" + pName, _aspectNames)} : {defVal},");
            }
            var helperName = $"__Deser_{nm}";
            writer.Block($"static {fullTypeName} {helperName}(object? __n, global::Catalyst.Registry.RegistrySet registries)");
            writer.Line($"if (!(__n is global::System.Collections.Generic.Dictionary<string, object?> __dict)) return new {fullTypeName}();");
            if (setters.Count > 0) {
                writer.Line($"return new {fullTypeName}");
                writer.Line("{");
                writer.Indent();
                foreach (var setter in setters) writer.Line(setter);
                writer.Unindent();
                writer.Line("};");
            } else {
                writer.Line($"return new {fullTypeName}();");
            }
            writer.EndBlock();
            deserIdx++;
        }

        // ── Populate method ──
        writer.Line(string.Empty);
        writer.Block("public static void Populate(global::Catalyst.Registry.RegistrySet registries)");
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(registries);");

        // Deserializer registrations
        foreach (var asp in _combinedAspects) {
            if (asp == null) continue;
            var nm = Helpers.Sanitize(asp.Name);
            var fullTypeName = $"global::{asp.Namespace}.{nm}";
            writer.Line($"registries.AspectTypes.Register(typeof({fullTypeName}));");
            var propParts = asp.PropertiesString.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
            if (propParts.Length > 0) {
                var fieldEntries = string.Join(", ", propParts.Select(FormatFieldEntry).Where(e => e.Length > 0));
                if (fieldEntries.Length > 0)
                    writer.Line($"registries.AspectFields.Register(\"{asp.Name}\", new global::System.Collections.Generic.Dictionary<string, global::System.Type> {{ {fieldEntries} }});");
            }
            var helperName = $"__Deser_{nm}";
            writer.Line($"registries.AspectTypes.RegisterDeserializer(typeof({fullTypeName}), (object __n) => {helperName}(__n, registries));");
        }

        // Being registrations
        foreach (var kv in _beingConcepts) {
            var en = Helpers.Sanitize(kv.Key);
            var typeArgs = string.Join(", ", kv.Value.Select(c => $"typeof({ConceptRef(c)})"));
            writer.Line($"registries.Beings.Register<global::Catalyst.Generated.{en}>({typeArgs});");
        }

        // Pool registrations
        foreach (var kv in _conceptAspects) {
            var cn = Helpers.Sanitize(kv.Key);
            if (!_conceptNames.Contains(kv.Key)) continue;
            var fas = new List<(string, string)>();
            foreach (var a in kv.Value) {
                if (_aspectDict.TryGetValue(a, out var aspInfo) && aspInfo != null)
                    fas.Add((Helpers.Sanitize(a), $"global::{aspInfo!.Namespace}.{Helpers.Sanitize(a)}"));
            }
            if (fas.Count == 0) continue;
            writer.Line($"registries.Beings.RegisterPool(typeof({ConceptRef(kv.Key)}), () => new {cn}Pool());");
        }

        // Ontology requires/suggests registrations
        if (hasOntology) {
            foreach (var conceptName in allOntologyConcepts) {
                var req = ontologyRequires.TryGetValue(conceptName, out var r) ? r : new List<string>();
                var sug = ontologySuggests.TryGetValue(conceptName, out var s) ? s : new List<string>();
                var reqArr = req.Count > 0
                    ? $"new string[] {{ {string.Join(", ", req.Select(a => $"\"{a}\""))} }}"
                    : "global::System.Array.Empty<string>()";
                var sugArr = sug.Count > 0
                    ? $"new string[] {{ {string.Join(", ", sug.Select(a => $"\"{a}\""))} }}"
                    : "global::System.Array.Empty<string>()";
                writer.Line($"registries.Requires.Register(\"{conceptName}\", {reqArr}, {sugArr});");
            }
        }

        writer.EndBlock(); // Populate
        writer.EndBlock(); // class
        writer.EndBlock(); // namespace
    }

    public void EmitBeingStructs(
        CodeWriter writer,
        SourceProductionContext spc) {
        if (_beingConcepts.Count == 0) return;
        writer.Line("#nullable enable");
        writer.Line("// <auto-generated/>");
        writer.Block("namespace Catalyst.Generated");
        foreach (var kv in _beingConcepts) {
            var en = Helpers.Sanitize(kv.Key);
            if (_beingDescriptions.TryGetValue(kv.Key, out var d))
                XmlDoc(writer, d);
            var ifaces = string.Join(", ", kv.Value.Select(c => $"global::Catalyst.IViewableAs<{ConceptRef(c)}>"));
            if (string.IsNullOrEmpty(ifaces))
                writer.Line($"public record struct {en} : global::Catalyst.IBeing {{ }}");
            else
                writer.Line($"public record struct {en} : global::Catalyst.IBeing, {ifaces} {{ }}");
        }
        writer.EndBlock();
    }

    public void EmitPools(
        CodeWriter writer,
        SourceProductionContext spc) {
        bool hasAny = false;
        foreach (var kv in _conceptAspects) {
            if (!_conceptNames.Contains(kv.Key)) continue;
            foreach (var a in kv.Value) {
                if (_aspectDict.ContainsKey(a)) { hasAny = true; break; }
            }
            if (hasAny) break;
        }
        if (!hasAny) return;

        writer.Line("#nullable enable");
        writer.Line("// <auto-generated/>");
        writer.Block("namespace Catalyst.Generated");
        foreach (var kv in _conceptAspects) {
            var cn = Helpers.Sanitize(kv.Key);
            if (!_conceptNames.Contains(kv.Key)) continue;
            var fas = new List<(string, string)>();
            foreach (var a in kv.Value) {
                if (_aspectDict.TryGetValue(a, out var aspInfo) && aspInfo != null)
                    fas.Add((Helpers.Sanitize(a), $"global::{aspInfo!.Namespace}.{Helpers.Sanitize(a)}"));
            }
            if (fas.Count == 0) continue;
            var sn = $"{cn}Aspects";

            // Aspect pool struct
            writer.Block($"public struct {sn}");
            foreach (var f in fas)
                writer.Line($"public {f.Item2} {f.Item1};");
            writer.Block("public ref readonly T Take<T>() where T : struct");
            writer.Line($"var ex = new global::System.ArgumentException($\"Aspect '{{typeof(T).Name}}' not found in {sn}\");");
            foreach (var f in fas)
                writer.Line($"if (typeof(T) == typeof({f.Item2})) return ref global::System.Runtime.CompilerServices.Unsafe.As<{f.Item2}, T>(ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in this.{f.Item1}));");
            writer.Line("throw ex;");
            writer.EndBlock(); // Take
            writer.EndBlock(); // struct

            // Pool class
            var setCases = string.Join(" ", fas.Select(f =>
                $"if (typeof(T) == typeof({f.Item2})) {{ _data[index].{f.Item1} = ({f.Item2})(object)value; return; }}"));
            var setRawCases = string.Join(" ", fas.Select(f =>
                $"if (type == typeof({f.Item2})) {{ _data[index].{f.Item1} = ({f.Item2})value; return; }}"));
            writer.Block($"public sealed class {cn}Pool : global::Catalyst.Storage.IStoragePool");
            writer.Line($"private {sn}[] _data = global::System.Array.Empty<{sn}>();");
            writer.Line("public int Count => _data.Length;");
            writer.Line("public void Resize(int size) => global::System.Array.Resize(ref _data, size);");
            writer.Line($"public ref readonly T Get<T>(int index) where T : struct {{ if (index < 0 || index >= _data.Length) throw new global::System.IndexOutOfRangeException(); return ref _data[index].Take<T>(); }}");
            writer.Line($"public void Set<T>(int index, T value) where T : struct {{ if (index < 0 || index >= _data.Length) throw new global::System.IndexOutOfRangeException(); {setCases} }}");
            writer.Line($"public void SetRaw(int index, global::System.Type type, object value) {{ if (index < 0 || index >= _data.Length) return; {setRawCases} }}");
            writer.Line("public void SetRawValue(int index, int aspectId, object? value) {{ }}");
            writer.Line("public object? GetRaw(int index, int aspectId) => null;");
            writer.EndBlock(); // class
        }
        writer.EndBlock(); // namespace
    }

    private static (string? Name, string? Type) ParsePropertyDef(string part) {
        var idx = part.IndexOf(':');
        if (idx <= 0) return (null, null);
        return (part.Substring(0, idx), part.Substring(idx + 1));
    }

    private static bool IsKnownValueType(string type) {
        var clean = type.TrimEnd('?');
        return clean.EndsWith("int") || clean.EndsWith("System.Int32") ||
            clean.EndsWith("long") || clean.EndsWith("System.Int64") ||
            clean.EndsWith("float") || clean.EndsWith("System.Single") ||
            clean.EndsWith("double") || clean.EndsWith("System.Double") ||
            clean.EndsWith("bool") || clean.EndsWith("System.Boolean");
    }

    private static string FormatFieldEntry(string propPart) {
        var idx = propPart.IndexOf(':');
        if (idx <= 0) return "";
        var name = propPart.Substring(0, idx);
        var type = propPart.Substring(idx + 1);
        return $"{{ \"{name}\", typeof({type}) }}";
    }

    public static JsonDataInfo ParseBeingFile(JsonElement root) {
        if (root.ValueKind != JsonValueKind.Object) return new JsonDataInfo(new BeingEntry[0]);
        if ((root.TryGetProperty("concepts", out var ck) && ck.ValueKind == JsonValueKind.Object) ||
            (root.TryGetProperty("aspects", out var ak) && ak.ValueKind == JsonValueKind.Object) ||
            (root.TryGetProperty("relations", out var rk) && rk.ValueKind == JsonValueKind.Object))
            return new JsonDataInfo(new BeingEntry[0]);

        var beings = new List<BeingEntry>();
        foreach (var beingProp in root.EnumerateObject()) {
            var beingKey = beingProp.Name;
            var beingObj = beingProp.Value;
            if (beingObj.ValueKind != JsonValueKind.Object) continue;

            string? description = null;
            if (beingObj.TryGetProperty("$description", out var descProp) && descProp.ValueKind == JsonValueKind.String)
                description = descProp.GetString();

            var fields = new List<BeingFieldInfo>();
            foreach (var prop in beingObj.EnumerateObject()) {
                if (prop.Name.Equals("$description", StringComparison.OrdinalIgnoreCase) ||
                    prop.Name.Equals("$inherits", StringComparison.OrdinalIgnoreCase) ||
                    prop.Name.Equals("inherits", StringComparison.OrdinalIgnoreCase))
                    continue;

                var nested = new List<string>();
                if (prop.Value.ValueKind == JsonValueKind.Object) {
                    foreach (var np in prop.Value.EnumerateObject())
                        nested.Add(np.Name);
                }
                nested.Sort();
                fields.Add(new BeingFieldInfo(prop.Name, nested.ToArray()));
            }
            beings.Add(new BeingEntry(beingKey, fields.ToArray(), new string[0], description));
        }
        return new JsonDataInfo(beings.ToArray());
    }
}
