namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;
using Microsoft.CodeAnalysis;

[DcPlugin(typeof(ITypeEmitter))]
public sealed class JsonRuntimeDataEmitter : ITypeEmitter {
	[ModuleInitializer]
	internal static void Register() => DcPluginRegistry.RegisterCompanion(new JsonRuntimeDataEmitter());

	public string Name => "JsonRuntime";

	public bool Applies(DcGenerationContext ctx) => ctx.Backend.HasFlag(DataBackend.Json);

	public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
		foreach (var col in schema.Columns) {
			if (col.Type.IsObject || col.Type.IsArray) {
				ctx.ReportDiagnostic(Diagnostic.Create(DcDiagnostics.JsonRuntimeFlatSchemaRequired, ctx.Location, ctx.TargetFullyQualifiedName, col.Name));
				return string.Empty;
			}
		}

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var ns = ctx.ContainingNamespace;
		if (!string.IsNullOrEmpty(ns)) {
			sb.Append("namespace ").Append(ns).AppendLine(";");
			sb.AppendLine();
		}

		var typeName = ctx.SimpleName;
		var enumName = typeName + "Kind";

		sb.Append("public static partial class ").Append(typeName).AppendLine("Json {");

		EmitReadMethod(sb, rows, schema, typeName, enumName);
		sb.AppendLine();
		EmitLoadAllMethod(sb, typeName);

		sb.AppendLine("}");
		sb.AppendLine();

		sb.Append("public sealed class ").Append(typeName).AppendLine("JsonRepository : global::FM39hz.DataCatalyst.Runtime.IDataRepository<" + enumName + ", " + typeName + "> {");
		sb.AppendLine("\tprivate readonly global::System.Collections.Generic.Dictionary<" + enumName + ", " + typeName + "> _data = new();");
		sb.AppendLine();
		sb.Append("\tpublic ").Append(typeName).AppendLine("JsonRepository(string filePath) {");
		sb.AppendLine("\t\tvar items = " + typeName + "Json.LoadAll(filePath);");
		sb.AppendLine("\t\tforeach (var item in items) {");
		sb.AppendLine("\t\t\t_data[item.Kind] = item;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\tpublic " + typeName + " Get(" + enumName + " kind) => _data[kind];");
		sb.AppendLine("\tpublic bool TryGet(" + enumName + " kind, out " + typeName + " value) => _data.TryGetValue(kind, out value!);");
		sb.AppendLine("\tpublic global::System.Collections.Generic.IEnumerable<" + typeName + "> GetAll() => _data.Values;");
		sb.AppendLine("\tpublic int Count => _data.Count;");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private static void EmitReadMethod(StringBuilder sb, IReadOnlyList<RowData> rows, SchemaInfo schema, string typeName, string enumName) {
		sb.Append("\tpublic static ").Append(typeName).AppendLine(" Read(ref global::System.Text.Json.Utf8JsonReader reader) {");
		sb.AppendLine("\t\treader.Read();");
		sb.Append("\t\tvar result = new ").Append(typeName).AppendLine("();");
		sb.AppendLine("\t\twhile (reader.Read() && reader.TokenType != global::System.Text.Json.JsonTokenType.EndObject) {");
		sb.AppendLine("\t\t\tvar propName = reader.GetString();");
		sb.AppendLine("\t\t\treader.Read();");
		sb.AppendLine("\t\t\tswitch (propName) {");

		sb.Append("\t\t\t\tcase \"Kind\": {");
		sb.Append(" var kindStr = reader.GetString(); ");
		sb.Append("switch (kindStr) {");
		for (var i = 0; i < rows.Count; i++) {
			sb.Append("case \"").Append(CodeEscapeString(rows[i].Key)).Append("\": result.Kind = ").Append(enumName).Append(".").Append(rows[i].Key).Append("; break; ");
		}

		sb.Append("default: throw new global::System.ArgumentException($\"Unknown 'Kind' value '{kindStr}' for '").Append(typeName).AppendLine("'\"); } break; }");

		foreach (var col in schema.Columns) {
			sb.Append("\t\t\t\tcase \"").Append(CodeEscapeString(col.Name)).Append("\": result.").Append(col.MemberName);
			sb.Append(" = ").Append(JsonAccessor(col.Type.Primitive)).AppendLine("; break;");
		}

		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\treturn result;");
		sb.AppendLine("\t}");
	}

	private static void EmitLoadAllMethod(StringBuilder sb, string typeName) {
		sb.Append("\tpublic static global::System.Collections.Generic.List<").Append(typeName).AppendLine("> LoadAll(string filePath) {");
		sb.AppendLine("\t\tvar bytes = global::System.IO.File.ReadAllBytes(filePath);");
		sb.Append("\t\tvar list = new global::System.Collections.Generic.List<").Append(typeName).AppendLine(">();");
		sb.AppendLine("\t\tvar reader = new global::System.Text.Json.Utf8JsonReader(bytes);");
		sb.AppendLine("\t\treader.Read();");
		sb.AppendLine("\t\twhile (reader.Read() && reader.TokenType != global::System.Text.Json.JsonTokenType.EndArray) {");
		sb.AppendLine("\t\t\tlist.Add(Read(ref reader));");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\treturn list;");
		sb.AppendLine("\t}");
	}

	private static string JsonAccessor(string? primitive) =>
		primitive switch {
			"int" => "reader.GetInt32()",
			"long" => "reader.GetInt64()",
			"float" => "reader.GetSingle()",
			"double" => "reader.GetDouble()",
			"bool" => "reader.GetBoolean()",
			"string" => "reader.GetString() ?? \"\"",
			"decimal" => "reader.GetDecimal()",
			_ => "reader.GetString() ?? \"\"",
		};

	private static string CodeEscapeString(string value) =>
		value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
