namespace FM39hz.DataCatalyst.Plugins.Emitters;

using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using FM39hz.DataCatalyst.Abstractions;
using FM39hz.DataCatalyst.Core;
using Microsoft.CodeAnalysis;

[DcPlugin(typeof(ITypeEmitter))]
public sealed class SqliteDataEmitter : ITypeEmitter {
	[ModuleInitializer]
	internal static void Register() => DcPluginRegistry.RegisterCompanion(new SqliteDataEmitter());

	public string Name => "Sqlite";

	public bool Applies(DcGenerationContext ctx) => ctx.Backend.HasFlag(DataBackend.Sqlite);

	public string Emit(IReadOnlyList<RowData> rows, SchemaInfo schema, DcGenerationContext ctx) {
		foreach (var col in schema.Columns) {
			if (col.Type.IsObject || col.Type.IsArray) {
				ctx.ReportDiagnostic(Diagnostic.Create(DcDiagnostics.SqliteFlatSchemaRequired, ctx.Location, ctx.TargetFullyQualifiedName, col.Name));
				return string.Empty;
			}
		}

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine();

		var ns = ctx.ContainingNamespace;
		if (!string.IsNullOrEmpty(ns)) {
			sb.Append("namespace ").Append(ns).AppendLine(";");
			sb.AppendLine();
		}

		var typeName = ctx.SimpleName;
		var enumName = typeName + "Kind";

		sb.Append("public static partial class ").Append(typeName).AppendLine("Sql {");

		sb.Append("\tpublic const string TableName = \"")
			.Append(EscapeSqlString(typeName)).AppendLine("\";");

		var colNames = new List<string>(schema.Columns.Length + 1) { "Kind" };
		foreach (var col in schema.Columns) {
			colNames.Add(col.Name);
		}

		sb.Append("\tpublic const string SelectAll = \"SELECT ");
		for (var ci = 0; ci < colNames.Count; ci++) {
			if (ci > 0) {
				sb.Append(", ");
			}

			sb.Append(EscapeSqlString(colNames[ci]));
		}

		sb.Append(" FROM ").Append(EscapeSqlString(typeName)).AppendLine("\";");

		sb.AppendLine();
		sb.AppendLine("\tpublic static global::System.Data.IDbCommand CreateSelectAllCommand(global::System.Data.IDbConnection conn) {");
		sb.AppendLine("\t\tvar cmd = conn.CreateCommand();");
		sb.AppendLine("\t\tcmd.CommandText = SelectAll;");
		sb.AppendLine("\t\treturn cmd;");
		sb.AppendLine("\t}");

		sb.AppendLine();
		sb.Append("\tpublic static ").Append(typeName).AppendLine(" ReadRow(global::System.Data.Common.DbDataReader reader) => new() {");
		sb.Append("\t\tKind = (").Append(enumName).AppendLine(")reader.GetInt32(0),");
		for (var i = 0; i < schema.Columns.Length; i++) {
			var col = schema.Columns[i];
			var ordinal = i + 1;
			var accessor = PrimitiveToSqliteAccessor(col.Type.Primitive);
			sb.Append("\t\t").Append(col.MemberName).Append(" = reader.").Append(accessor).Append('(').Append(ordinal.ToString(CultureInfo.InvariantCulture)).AppendLine("),");
		}

		sb.AppendLine("\t};");
		sb.AppendLine("}");
		sb.AppendLine();

		sb.Append("public sealed class ").Append(typeName).AppendLine("SqlRepository : global::FM39hz.DataCatalyst.Runtime.IDataRepository<" + enumName + ", " + typeName + "> {");
		sb.AppendLine("\tprivate readonly global::System.Func<global::System.Data.IDbConnection> _connectionFactory;");
		sb.AppendLine("\tprivate readonly global::System.Collections.Generic.Dictionary<" + enumName + ", " + typeName + "> _data = new();");
		sb.AppendLine("\tprivate bool _loaded;");
		sb.AppendLine("\tprivate readonly object _loadLock = new();");
		sb.AppendLine();
		sb.AppendLine("\tpublic " + typeName + "SqlRepository(global::System.Func<global::System.Data.IDbConnection> connectionFactory) {");
		sb.AppendLine("\t\t_connectionFactory = connectionFactory;");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\tprivate void EnsureLoaded() {");
		sb.AppendLine("\t\tif (_loaded) return;");
		sb.AppendLine("\t\tlock (_loadLock) {");
		sb.AppendLine("\t\t\tif (_loaded) return;");
		sb.AppendLine("\t\t\tusing var conn = _connectionFactory();");
		sb.AppendLine("\t\t\tconn.Open();");
		sb.AppendLine("\t\t\tusing var cmd = " + typeName + "Sql.CreateSelectAllCommand(conn);");
		sb.AppendLine("\t\t\tusing var reader = cmd.ExecuteReader();");
		sb.AppendLine("\t\t\twhile (reader.Read()) {");
		sb.AppendLine("\t\t\t\tvar item = " + typeName + "Sql.ReadRow((global::System.Data.Common.DbDataReader)reader);");
		sb.AppendLine("\t\t\t\t_data[item.Kind] = item;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\t_loaded = true;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();
		sb.AppendLine("\tpublic " + typeName + " Get(" + enumName + " kind) { EnsureLoaded(); return _data[kind]; }");
		sb.AppendLine("\tpublic bool TryGet(" + enumName + " kind, out " + typeName + " value) { EnsureLoaded(); return _data.TryGetValue(kind, out value!); }");
		sb.AppendLine("\tpublic global::System.Collections.Generic.IEnumerable<" + typeName + "> GetAll() { EnsureLoaded(); return _data.Values; }");
		sb.AppendLine("\tpublic int Count { get { EnsureLoaded(); return _data.Count; } }");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private static string EscapeSqlString(string raw) => raw.Replace("\"", "\"\"");

	private static string PrimitiveToSqliteAccessor(string? primitive) =>
		primitive switch {
			"int" => "GetInt32",
			"long" => "GetInt64",
			"float" => "GetFloat",
			"double" => "GetDouble",
			"bool" => "GetBoolean",
			"string" => "GetString",
			"decimal" => "GetDecimal",
			_ => "GetString",
		};
}
