namespace DataCatalyst.Core;

using System;
using System.Collections.Generic;
using System.Linq;
using DataCatalyst.Abstractions;
using DataCatalyst.Core;

/// <summary>
/// Plugin that builds concept-scoped catalogs after catalog resolution.
/// Concept membership is declared by each entry via the "concept" field in data files.
/// Concept types are declared in concepts.json and auto-generated by SourceGen.
/// </summary>
[DataPlugin]
public sealed class GameConceptPlugin : ICatalogPlugin {
	private readonly Dictionary<Type, object> _conceptCatalogs = [];

	/// <inheritdoc/>
	public bool IsEnabled => true;

	/// <inheritdoc/>
	public void OnLoad() { }

	/// <summary>The concept registry (defaults to ConceptRegistry.Default).</summary>
	public ConceptRegistry Registry => ConceptRegistry.Default;

	/// <summary>Gets a concept-scoped catalog by tag type.</summary>
	public ConceptCatalog<TConcept> GetConcept<TConcept>() where TConcept : struct {
		if (_conceptCatalogs.TryGetValue(typeof(TConcept), out var catalog) &&
			catalog is ConceptCatalog<TConcept> typed) {
			return typed;
		}
		throw new InvalidOperationException(
			$"Concept '{typeof(TConcept).Name}' not registered. " +
			"Ensure a [DataConcept] attribute or concepts.json entry exists.");
	}

	/// <summary>
	/// Called after catalog resolution. Builds concept-scoped catalogs
	/// by grouping entries by their ConceptName field.
	/// </summary>
	public void OnCatalogResolved(DataCatalog catalog, List<string> diagnostics) {
		var conceptGroups = new Dictionary<string, Dictionary<int, DataEntry>>();

		foreach (var entry in catalog.Entries.Values) {
			if (!entry.TryGet<Concept>(out var concept)) continue;
			var names = concept.Value;
			if (names == null || names.Length == 0) continue;

			foreach (var conceptName in names) {
				if (string.IsNullOrEmpty(conceptName)) continue;
				if (!conceptGroups.TryGetValue(conceptName, out var group)) {
					group = new Dictionary<int, DataEntry>();
					conceptGroups[conceptName] = group;
				}
				var entryId = catalog.GetEntryId(entry.Key);
				if (entryId >= 0) group[entryId] = entry;
			}
		}

		foreach (var kv in ConceptRegistry.Default) {
			var tagType = kv.Key;
			var name = kv.Value;

			if (!conceptGroups.TryGetValue(name, out var entries)) {
				continue;
			}

			var conceptCatalog = CreateConceptCatalog(tagType, entries, name);
			if (conceptCatalog != null) {
				_conceptCatalogs[tagType] = conceptCatalog;
			}
		}
	}

	private object? CreateConceptCatalog(Type tagType, Dictionary<int, DataEntry> entries, string conceptName) {
		var catalog = Registry.CreateCatalog(tagType, entries, conceptName);
		if (catalog != null) return catalog;

		return Fallback(tagType, entries, conceptName);
	}

#if NET6_0_OR_GREATER
	[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("ReflectionAnalysis", "IL2055:UniquenessOfRuntimeType", Justification = "Fallback for non-AOT environments")]
	[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("ReflectionAnalysis", "IL3050:AotCall", Justification = "Fallback for non-AOT environments")]
	[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("ReflectionAnalysis", "IL2071:UnresolvedGenericRequirement", Justification = "Fallback for non-AOT environments")]
#endif
	private static object? Fallback(Type t, Dictionary<int, DataEntry> e, string n) {
		var catalogType = typeof(ConceptCatalog<>).MakeGenericType(t);
		return Activator.CreateInstance(catalogType,
			System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public,
			null,
			[e, n],
			null);
	}
}
