namespace FM39hz.DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class UniversalDataGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddSource("DataPluginAttribute.g.cs", SourceText.From("""
                using System;

                [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
                public sealed class DataPluginAttribute : Attribute {
                    public string Id { get; }
                    public string[]? DependsOn { get; init; }
                    public DataPluginAttribute(string id) => Id = id;
                }

                public static class DepParser {
                    public static (string Name, int Major, int Minor, int Patch) Parse(string dep) {
                        var at = dep.LastIndexOf('@');
                        if (at < 0) return (dep, 0, 0, 0);
                        var name = dep.Substring(0, at);
                        var ver = dep.Substring(at + 1);
                        var parts = ver.Split('.');
                        var major = parts.Length > 0 && int.TryParse(parts[0], out var m) ? m : 0;
                        var minor = parts.Length > 1 && int.TryParse(parts[1], out var n) ? n : 0;
                        var patch = parts.Length > 2 && int.TryParse(parts[2], out var p) ? p : 0;
                        return (name, major, minor, patch);
                    }
                    public static bool Satisfies(string required, string available) {
                        var (_, rMajor, rMinor, rPatch) = Parse(required);
                        var (_, aMajor, aMinor, aPatch) = Parse(available);
                        if (rMajor == 0) return true;
                        if (aMajor != rMajor) return false;
                        if (aMinor > rMinor) return true;
                        if (aMinor < rMinor) return false;
                        return aPatch >= rPatch;
                    }
                }

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class ModPluginAttribute : Attribute {
                    public string Name { get; }
                    public string[] Dependencies { get; }
                    public ModPluginAttribute(string name, string[] dependencies = null) {
                        Name = name;
                        Dependencies = dependencies ?? [];
                    }
                }
                """, Encoding.UTF8));

            ctx.AddSource("DataDslAttribute.g.cs", SourceText.From("""
                using System;

                [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
                public sealed class DataDslAttribute : Attribute {
                    public string Id { get; }
                    public Type SchemaType { get; }
                    public DataDslAttribute(string id, Type schemaType) {
                        Id = id;
                        SchemaType = schemaType;
                    }
                }
                """, Encoding.UTF8));
        });

        // Collect IDataPlugin types (classes implementing IDataPlugin in FM39hz.DataCatalyst.Abstractions)
        var plugins = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ExtractPlugin(ctx))
            .Where(static p => p is not null)
            .Select(static (p, _) => p!.Value)
            .Collect();

        context.RegisterSourceOutput(plugins, static (spc, list) => {
            if (list.IsDefaultOrEmpty) return;
            var sorted = TopoSort(list);

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n\nnamespace FM39hz.DataCatalyst.Runtime {\n\tpublic static partial class PluginRegistrations {\n");
            sb.Append("\t\t[System.Runtime.CompilerServices.ModuleInitializer]\n\t\tinternal static void Init() {\n");
            foreach (var (fullType, id, dependsOn) in sorted) {
                var sanitized = System.Text.RegularExpressions.Regex.Replace(id, "[^a-zA-Z0-9]", "_");
                sb.Append("\t\t\tglobal::FM39hz.DataCatalyst.Runtime.PluginRegistry.Register<global::")
                  .Append(fullType).AppendLine(">();");
            }
            sb.Append("\t\t}\n\t}\n}");
            spc.AddSource("PluginRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });

        // Legacy: support old [ModPlugin] too
        var modPlugins = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "FM39hz.DataCatalyst.ModPluginAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ExtractModPlugin(ctx))
            .Where(static p => p.HasValue)
            .Select(static (p, _) => p!.Value)
            .Collect();

        context.RegisterSourceOutput(modPlugins, static (spc, plugins) => {
            if (plugins.IsDefaultOrEmpty) return;
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n\nnamespace FM39hz.DataCatalyst.Runtime {\n\tpublic static partial class ModPluginRegistrations {\n");
            var seen = new HashSet<string>();
            foreach (var (name, fullType, _) in plugins) {
                if (!seen.Add(name)) continue;
                sb.Append("\t\t[System.Runtime.CompilerServices.ModuleInitializer]\n");
                sb.Append("\t\tinternal static void Register_")
                  .Append(System.Text.RegularExpressions.Regex.Replace(name, "[^a-zA-Z0-9]", "_")).Append("() =>\n");
                sb.Append("\t\t\tglobal::FM39hz.DataCatalyst.Runtime.PluginRegistry.RegisterLegacy(new global::")
                  .Append(fullType).AppendLine("());\n");
            }
            sb.Append("\t}\n}");
            spc.AddSource("ModPluginRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static (string FullType, string Id, string[] DependsOn)? ExtractPlugin(GeneratorSyntaxContext ctx) {
        if (ctx.Node is not ClassDeclarationSyntax cds) return null;
        var model = ctx.SemanticModel;
        var type = model.GetDeclaredSymbol(cds) as INamedTypeSymbol;
        if (type is null) return null;
        if (!type.AllInterfaces.Any(i => i.Name == "IDataPlugin")) return null;

        // Find the [DataPlugin] assembly attribute
        string id = type.Name;
        string[] dependsOn = [];
        foreach (var attr in type.ContainingAssembly.GetAttributes()) {
            if (attr.AttributeClass?.Name == "DataPluginAttribute" && attr.ConstructorArguments.Length == 1) {
                id = attr.ConstructorArguments[0].Value as string ?? type.Name;
                if (attr.NamedArguments.Length > 0) {
                    foreach (var na in attr.NamedArguments) {
                        if (na.Key == "DependsOn" && na.Value.Values is { Length: > 0 } vs) {
                            var list = new List<string>();
                            foreach (var v in vs) {
                                var s = v.Value?.ToString();
                                if (!string.IsNullOrEmpty(s)) list.Add(s!);
                            }
                            dependsOn = [.. list];
                        }
                    }
                }
                break;
            }
        }

        var fullType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return (fullType, id, dependsOn);
    }

    private static (string FullType, string Id, string[] DependsOn)[] TopoSort(
        ImmutableArray<(string FullType, string Id, string[] DependsOn)> plugins) {

        var map = new Dictionary<string, (string FullType, string Id, string[] DependsOn)>();
        var indegree = new Dictionary<string, int>();
        var edges = new Dictionary<string, List<string>>();

        foreach (var p in plugins) {
            map[p.Id] = p;
            indegree[p.Id] = 0;
            edges[p.Id] = [];
        }

        foreach (var p in plugins) {
            foreach (var dep in p.DependsOn) {
                if (!map.ContainsKey(dep)) continue;
                edges[dep].Add(p.Id);
                indegree[p.Id]++;
            }
        }

        var ready = new List<(string FullType, string Id, string[] DependsOn)>();
        foreach (var p in plugins) {
            if (!indegree.TryGetValue(p.Id, out var deg) || deg == 0) ready.Add(p);
        }

        var sorted = new List<(string FullType, string Id, string[] DependsOn)>();
        while (ready.Count > 0) {
            var cur = ready[0]; ready.RemoveAt(0);
            sorted.Add(cur);
            foreach (var child in edges.TryGetValue(cur.Id, out var childList) ? childList : []) {
                indegree[child]--;
                if (indegree[child] == 0 && map.TryGetValue(child, out var next))
                    ready.Add(next);
            }
        }

        // Append any remaining (cyclic deps)
        foreach (var p in plugins) {
            if (!sorted.Contains(p)) sorted.Add(p);
        }

        return [.. sorted];
    }

    private static (string Name, string FullType, string[] Dependencies)? ExtractModPlugin(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
        AttributeData? attr = null;
        foreach (var a in ctx.Attributes) { attr = a; break; }
        if (attr is null) return null;

        var name = string.Empty;
        var dependencies = System.Array.Empty<string>();

        if (attr.ConstructorArguments.Length >= 1 && attr.ConstructorArguments[0].Value is string n) name = n;
        if (attr.ConstructorArguments.Length >= 2 && attr.ConstructorArguments[1].Values is var deps) {
            var list = new List<string>();
            foreach (var d in deps) {
                var s = d.Value?.ToString();
                if (!string.IsNullOrEmpty(s)) list.Add(s!);
            }
            dependencies = [.. list];
        }
        foreach (var na in attr.NamedArguments) {
            switch (na.Key) {
                case "Name" when na.Value.Value is string ns: name = ns; break;
                case "Dependencies" when na.Value.Values is { Length: > 0 } vs:
                    var list = new List<string>();
                    foreach (var v in vs) {
                        var s = v.Value?.ToString();
                        if (!string.IsNullOrEmpty(s)) list.Add(s!);
                    }
                    dependencies = [.. list];
                    break;
            }
        }
        if (string.IsNullOrEmpty(name)) name = type.Name;
        var fullType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return (Name: name, FullType: fullType, Dependencies: dependencies);
    }
}
