namespace FM39hz.DataCatalyst;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class UniversalDataGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Emit runtime attributes
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddSource("DepParser.g.cs", SourceText.From("""
                using System;

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class ModPluginAttribute : Attribute {
                    public string Name { get; }
                    public string[] Dependencies { get; }
                    public ModPluginAttribute(string name, string[] dependencies = null) {
                        Name = name;
                        Dependencies = dependencies ?? [];
                    }
                }

                public static class DepParser {
                    public static (string Name, int Major, int Minor, int Patch) Parse(string dep) {
                        var at = dep.LastIndexOf('@');
                        if (at < 0) return (dep, 0, 0, 0);
                        var name = dep.Substring(0, at);
                        var ver = dep.Substring(at + 1);
                        var parts = ver.Split('.');
                        var major = parts.Length > 0 && int.TryParse(parts[0], out var m) ? m : 0;
                        var minor = parts.Length > 1 && int.TryParse(parts[1], out var n) ? n : 0;
                        var patch = parts.Length > 2 && int.TryParse(parts[2], out var p) ? p : 0;
                        return (name, major, minor, patch);
                    }
                    public static bool Satisfies(string required, string available) {
                        var (_, rMajor, rMinor, rPatch) = Parse(required);
                        var (_, aMajor, aMinor, aPatch) = Parse(available);
                        if (rMajor == 0) return true;
                        if (aMajor != rMajor) return false;
                        if (aMinor > rMinor) return true;
                        if (aMinor < rMinor) return false;
                        return aPatch >= rPatch;
                    }
                }
                """, Encoding.UTF8));
        });

        // Collect [ModPlugin] classes
        var modPlugins = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "FM39hz.DataCatalyst.ModPluginAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ExtractModPlugin(ctx))
            .Where(static p => p.HasValue)
            .Select(static (p, _) => p!.Value)
            .Collect();

        context.RegisterSourceOutput(modPlugins, static (spc, plugins) => {
            if (plugins.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n\nnamespace FM39hz.DataCatalyst.Runtime;\n\npublic static partial class ModPluginRegistrations {\n");
            var seen = new HashSet<string>();
            foreach (var (name, fullType, _) in plugins) {
                if (!seen.Add(name)) continue;
                sb.Append("\t[System.Runtime.CompilerServices.ModuleInitializer]\n");
                var sanitized = System.Text.RegularExpressions.Regex.Replace(name, "[^a-zA-Z0-9]", "_");
                sb.Append("\tinternal static void Register_").Append(sanitized).Append("() =>\n");
                sb.Append("\t\tglobal::FM39hz.DataCatalyst.Runtime.PluginRegistry.Register(new ").Append(fullType).AppendLine("());\n");
            }
            sb.Append("}");
            spc.AddSource("ModPluginRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static (string Name, string FullType, string[] Dependencies)? ExtractModPlugin(GeneratorAttributeSyntaxContext ctx) {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
        AttributeData? attr = null;
        foreach (var a in ctx.Attributes) { attr = a; break; }
        if (attr is null) return null;

        var name = string.Empty;
        var dependencies = System.Array.Empty<string>();

        if (attr.ConstructorArguments.Length >= 1 && attr.ConstructorArguments[0].Value is string n) name = n;
        if (attr.ConstructorArguments.Length >= 2 && attr.ConstructorArguments[1].Values is var deps) {
            var list = new List<string>();
            foreach (var d in deps) {
                var s = d.Value?.ToString();
                if (!string.IsNullOrEmpty(s)) list.Add(s!);
            }
            dependencies = [.. list];
        }
        foreach (var na in attr.NamedArguments) {
            switch (na.Key) {
                case "Name" when na.Value.Value is string ns: name = ns; break;
                case "Dependencies" when na.Value.Values is { Length: > 0 } vs:
                    var list = new List<string>();
                    foreach (var v in vs) {
                        var s = v.Value?.ToString();
                        if (!string.IsNullOrEmpty(s)) list.Add(s!);
                    }
                    dependencies = [.. list];
                    break;
            }
        }

        if (string.IsNullOrEmpty(name)) name = type.Name;
        var fullType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return (Name: name, FullType: fullType, Dependencies: dependencies);
    }
}
